// PHHC Case Type Value Mapping
// Maps full case type text to case type code for dropdown selection
const PHHC_CASE_TYPES_VALUE_MAPPING = {
  "CWP-:(CIVIL WRIT PETITION)": "CWP",
  "CRM-M-:(CRIMINAL MAIN)": "CRM-M",
  "CR-:(CIVIL REVISION)": "CR",
  "RSA-:(REGULAR SECOND APPEAL)": "RSA",
  "CRR-:(CRIMINAL REVISION)": "CRR",
  "CRA-S-:(CRIMINAL APPEAL SB)": "CRA-S",
  "FAO-:(FIRST APPEAL ORDER)": "FAO",
  "CM-:(CIVIL MISC)": "CM",
  "CRM-:(CRIMINAL MISCELLANEOUS PETITION)": "CRM",
  "ARB-:(ARBITRATION ACT CASE (WEF 15/10/03))": "ARB",
  "ARB-DC-:(ARBITRATION CASE (DOMESTIC COMMERCIAL))": "ARB-DC",
  "ARB-ICA-:(ARBITRATION CASE(INTERNATIONAL COMM. ARBITRATION))": "ARB-ICA",
  "CA-:(CIVIL APPEAL/COMPANY APPLICATION)": "CA",
  "CA-CWP-:(COMMERCIAL APPEAL (WRIT))": "CA-CWP",
  "CA-MISC-:(COMMERCIAL APPEAL (MISC))": "CA-MISC",
  "CACP-:(CONTEMPT APPEALS)": "CACP",
  "CAPP-:(COMPANY APPEAL)": "CAPP",
  "CCEC-:(CUSTOM CENTRAL EXCISE CASE)": "CCEC",
  "CCES-:(CCES)": "CCES",
  "CEA-:(CENTRAL EXCEISE APPEAL (WEF 10-11-2003))": "CEA",
  "CEC-:(CENTRAL EXCISE CASE)": "CEC",
  "CEGC-:(CENTRAL EXCISE GOLD CASE)": "CEGC",
  "CESR-:(CENTRAL EXCISE AND SALT REFERENCE)": "CESR",
  "CLAIM-:(CLAIMS)": "CLAIM",
  "CM-INCOMP-:(Misc. Appl. in Incomplete Case)": "CM-INCOMP",
  "CMA-:(COMPANY MISC. APPLICATION)": "CMA",
  "CMM-:(HMA CASES U/S 24)": "CMM",
  "CO-:(CIVIL ORIGINAL)": "CO",
  "CO-COM-:(CIVIL ORIGINAL (COMMERCIAL))": "CO-COM",
  "COA-:(COMPANY APPLICATION)": "COA",
  "COCP-:(CIVIL ORIGINAL CONTEMPT PETITION)": "COCP",
  "COMM-PET-M-:(COMMERCIAL PETITION MAIN)": "COMM-PET-M",
  "CP-:(COMPANY PETITIONS)": "CP",
  "CP-MISC-:(COMMERCIAL PETITON (MISC))": "CP-MISC",
  "CR-COM-:(CIVIL REVISION (COMMERCIAL))": "CR-COM",
  "CRA-:(CRIMINAL APPEAL)": "CRA",
  "CRA-AD-:(CRIMINAL APPEAL ACQUITTAL DB)": "CRA-AD",
  "CRA-AS-:(CRIMINAL APPEAL ACQUITTAL SB)": "CRA-AS",
  "CRA-D-:(CRIMINAL APPEAL DB)": "CRA-D",
  "CRACP-:(CRIMINAL APPEAL CONTEMPT PETITION)": "CRACP",
  "CREF-:(CIVIL REFERENCE)": "CREF",
  "CRM-A-:(AGAINST ACQUITTALS)": "CRM-A",
  "CRM-CLT-OJ-:(CRIMINAL COMPLAINT (ORIGINAL SIDE))": "CRM-CLT-OJ",
  "CRM-W-:(CRM IN CRWP)": "CRM-W",
  "CROCP-:(CRIMINAL ORIGINAL CONTEMPT PETITION)": "CROCP",
  "CRR(F)-:(CRIMINAL REVISION (FAMILY COURT))": "CRR(F)",
  "CRREF-:(CRIMINAL REFERENCE)": "CRREF",
  "CRWP-:(CRIMINAL WRIT PETITION)": "CRWP",
  "CS-:(CIVIL SUIT)": "CS",
  "CS-OS-:(CIVIL SUIT-ORIGINAL SIDE)": "CS-OS",
  "CUSAP-:(CUSTOM APPEAL (WEF 17/7/2004))": "CUSAP",
  "CWP-COM-:(CIVIL WRIT PETITION (COMMERCIAL))": "CWP-COM",
  "CWP-PIL-:(CIVIL WRIT PETITION PUBLIC INTEREST LITIGATION)": "CWP-PIL",
  "DP-:(DIVORCE PETITION)": "DP",
  "EA-:(EXECUTION APPL.)": "EA",
  "EDC-:(ESTATE DUTY CASE)": "EDC",
  "EDREF-:(ESTATE DUTY REFERENCE)": "EDREF",
  "EFA-:(EXECUTION FIRST APPEAL)": "EFA",
  "EFA-COM-:(EXECUTION FIRST APPEAL (COMMERCIAL))": "EFA-COM",
  "EP-:(ELECTION PETITIONS)": "EP",
  "EP-COM-:(EXECUTION PETITION (COMMERCIAL))": "EP-COM",
  "ESA-:(EXECUTION SECOND APPEAL)": "ESA",
  "FAO(FC)-:(FAO (FAMILY COURT))": "FAO(FC)",
  "FAO-C-:(FAO (CUS AND MTC))": "FAO-C",
  "FAO-CARB-:(FIRST APPEAL FROM ORDER (COMMERCIAL ARBITRATION))": "FAO-CARB",
  "FAO-COM-:(FIRST APPEAL FROM ORDER (COMMERCIAL))": "FAO-COM",
  "FAO-ICA-:(FIRST APPEAL FROM ORDER(INTERNATIONAL COMM.ARBI.))": "FAO-ICA",
  "FAO-M-:(FIRST APPEAL ORDER-MATRIMONIAL)": "FAO-M",
  "FEMA-APPL-:(FEMA APPEAL)": "FEMA-APPL",
  "FORM-8A-:(FORM-8A)": "FORM-8A",
  "GCR-:(GOLD CONTROL REFERENCE)": "GCR",
  "GSTA-:(GOODS AND SERVICES TAX APPEAL)": "GSTA",
  "GSTR-:(GENERAL SALES TAX REFERENCE)": "GSTR",
  "GTA-:(GIFT TAX APPEAL)": "GTA",
  "GTC-:(GIFT TAX CASE)": "GTC",
  "GTR-:(GIFT TAX REFERENCE)": "GTR",
  "GVATR-:(GENERAL VAT REFERENCES)": "GVATR",
  "INCOMP-:(INCOMPLETE OBJECTION CASE)": "INCOMP",
  "INTTA-:(INTEREST TAX APPEAL)": "INTTA",
  "IOIN-:(INTERIM ORDER IN)": "IOIN",
  "ITA-:(INCOME TAX APPEAL)": "ITA",
  "ITC-:(INCOME TAX CASES)": "ITC",
  "ITR-:(INCOME TAX REFERENCE)": "ITR",
  "LPA-:(LETTER PATENT APPEAL)": "LPA",
  "LR-:(LIQUIDATOR REPORT)": "LR",
  "MATRF-:(MATROMONIAL REFERENCE)": "MATRF",
  "MRC-:(MURDER REFERENCE CASE)": "MRC",
  "O&M-:(ORIGINAL & MISCELLANEOUS)": "O&M",
  "OLR-:(OFFICIAL LIQUIDATOR REPORT)": "OLR",
  "PBPT-APPL-:(PROHIBITION OF BENAMI PROPERTY TRANSACTION APPEAL)": "PBPT-APPL",
  "PBT-:(PROBATE)": "PBT",
  "PMLA-APPL-:(PREVENTION OF MONEY LAUNDERING APPEAL)": "PMLA-APPL",
  "PVR-:(PB VAT REVISION)": "PVR",
  "RA-:(REVIEW APPL)": "RA",
  "RA-CA-:(REVIEW IN COMPANY APPEAL)": "RA-CA",
  "RA-CP-:(REVIEW IN COMPANY PETITION.)": "RA-CP",
  "RA-CR-:(REVIEW IN CR)": "RA-CR",
  "RA-CW-:(REVIEW IN CWP)": "RA-CW",
  "RA-LP-:(REVIEW IN LPA)": "RA-LP",
  "RA-RF-:(REVIEW APPLICATION IN RFA)": "RA-RF",
  "RA-RS-:(REVIEW IN RSA)": "RA-RS",
  "RCRWP-:(REVIEW IN CRCWP)": "RCRWP",
  "RERA-APPL-:(RERA APPEAL)": "RERA-APPL",
  "RFA-:(REGULAR FIRST APPEAL)": "RFA",
  "RFA-COM-:(REGULAR FIRST APPEAL (COMMERCIAL))": "RFA-COM",
  "RP-:(RECRIMINATION PETITION)": "RP",
  "SA-:(SERVICE APPEAL)": "SA",
  "SAO-:(SECOND APPEAL ORDER)": "SAO",
  "SAO(FS)-:(SAO FOOD SAFETY)": "SAO(FS)",
  "SDR-:(STATE DUTY REFERENCE)": "SDR",
  "STA-:(SALES TAX APPEAL)": "STA",
  "STC-:(SALES TAX CASES)": "STC",
  "STR-:(SALE TAX REFERENCE)": "STR",
  "TA-:(TRANSFER APPLICATION)": "TA",
  "TA-COM-:(TRANSFER APPLICATION (COMMERCIAL))": "TA-COM",
  "TC-:(TAKENUP CASES)": "TC",
  "TCRM-:(TRANSFER CRIMINAL PETITION)": "TCRM",
  "TEST-:(TEST)": "TEST",
  "UVA-:(UT VAT APPEAL)": "UVA",
  "UVR-:(UT VAT REVISION)": "UVR",
  "VATAP-:(VAT APPEAL)": "VATAP",
  "VATCASE-:(VALUE ADDED TAX CASE)": "VATCASE",
  "VATREF-:(VAT REFERENCE)": "VATREF",
  "WTA-:(WEALTH TAX APPEAL)": "WTA",
  "WTC-:(WEALTH TAX CASES)": "WTC",
  "WTR-:(WEALTH TAX REFERENCE)": "WTR",
  "XOBJ-:(CROSS OBJECTION)": "XOBJ",
  "XOBJC-:(CROSS OBJECTION IN CR)": "XOBJC",
  "XOBJL-:(CROSS OBJECTION IN LPA)": "XOBJL",
  "XOBJR-:(CROSS OBJECTION IN RFA)": "XOBJR",
  "XOBJS-:(CROSS OBJECTION IN RSA)": "XOBJS",
};

/**
 * Get case type code from full case type text
 * @param {string} caseTypeText - Full case type text (e.g., "CWP-:(CIVIL WRIT PETITION)")
 * @returns {string|null} - Case type code (e.g., "CWP") or null if not found
 */
function getCaseTypeCode(caseTypeText) {
  if (!caseTypeText) {
    return null;
  }
  
  // Try exact match first
  if (PHHC_CASE_TYPES_VALUE_MAPPING[caseTypeText]) {
    return PHHC_CASE_TYPES_VALUE_MAPPING[caseTypeText];
  }
  
  // If already a code (not in mapping), return as-is
  // This handles cases where the database already has the code
  if (!caseTypeText.includes('-:(')) {
    return caseTypeText;
  }
  
  // If not found, return null
  return null;
}

module.exports = {
  PHHC_CASE_TYPES_VALUE_MAPPING,
  getCaseTypeCode
};

