const delhiCourts = {
   "eastdelhi":{
      "Karkardooma Court Complex":[
         "1 Ms. Sukhvinder Kaur - Principal District and Sessions Judge, East District",
         "4 Ms. APARNA SWAMI - Presiding Off.-MACT",
         "17 Sh. Ramesh Kumar-II - Additional Sessions Judge",
         "49 Sh. Ravinder Singh-I - District Judge",
         "419 Sh. Hem Singh - District Judge",
         "463 Ms. Manu Vedwan - ASJ/SPECIAL.JUDGE(NDPS)",
         "466 Ms. Swati Katiyar - Additional Sessions Judge",
         "474 Sh. Subhash Kumar Mishra - Additional Sessions Judge",
         "482 Ms. Shuchi Laler - District Judge",
         "763 Sh. Ashish Rastogi - Additional Sessions Judge",
         "764 Ms. Vasundhra Chhaunkar - Additional Sessions Judge",
         "765 Sh. Akash Jain - Additional Sessions Judge",
         "767 Sh. Devender Kumar - District Judge (Commercial Court)",
         "768 Ms. Vidhi Gupta Anand - Additional Sessions Judge",
         "769 Ms. Ruby Alka Gupta - District Judge (Commercial Court) 02",
         "770 Sh. Jitendra Pratap Singh - Additional Sessions Judge",
         "771 Ms. Snigdha Sarvaria - Additional Sessions Judge",
         "772 Sh. Rakesh Kumar Rampuri - Additional Sessions Judge",
         "774 Sh. Sonu Agnihotri - District Judge",
         "776 Sh. Vikas Garg - District Judge",
         "777 Sh. Somitra Kumar - District Judge",
         "778 Sh. Anurag Thakur - Additional Sessions Judge",
         "12 Sh. Rinku Jain - Addl. Chief Judicial Magistrate",
         "16 Ms. Prigya Gupta - Chief Judicial Magistrate",
         "24 Sh. Pritu Raj - Judicial Magistrate First Class",
         "34 Ms. Sonam Singh II - Judicial Magistrate First Class (Mahila Court)-01",
         "435 Sh. Satendra Pal Singh - Judicial Magistrate First Class",
         "439 Sh. Sachin - Judicial Magistrate First Class",
         "446 Sh. Divyam Lila - Municipal Magistrate",
         "451 Sh. Ankit Solanki - Judicial Magistrate First Class NI Act-01",
         "461 Ms. Ritika Kansal - Judicial Magistrate First Class (Mahila Court)-02",
         "471 Ms. Prerna Rai - Judicial Magistrate First Class",
         "762 Sh. P. Bhargav Rao - Judicial Magistrate First Class",
         "763 Sh. Sidhant Krishan Singh - Judicial Magistrate First Class (NI Act) Digital Court",
         "764 Sh. Kunal Soni - Judicial Magistrate First Class (Digital Traffic Court)",
         "766 Ms. Sanya Singh - Judicial Magistrate First Class",
         "767 Sh. Pritu Raj - Judicial Magistrate First Class Evening Court-4",
         "768 Ms. Shraddha Tripathi - Judicial Magistrate First Class NI Act-02",
         "63 Sh. Vivek Beniwal - Senior Civil Judge",
         "66 Sh. Vinik Jain - ACJ/CCJ/ARC",
         "76 Dr. Saema Jain - Judge-Small Cause Court",
         "762 Sh. Ayush Sharma - Civil Judge",
         "1 Sh. Manish Khurana - Judge, Family Court -01 , East Distt.",
         "2 Sh. Sanjeev Kumar Aggarwal - Principal Judge, Family Court, East Dist.",
         "3 Sh. Pawan Singh Rajawat - Judge Family Court 02",
         "1 Sh. Sahil Khurmi - Principal Magistrate JJB-IV"
      ]
   },
   "newdelhi":{
      "Patiala House Court Complex":[
         "1 Ms. Anju Bajaj Chandna - Principal District and Sessions Judge",
         "10 Ms. Deepti Devesh - Additional Sessions Judge (SFTC)",
         "11 Ms. Ruby Neeraj Kumar - Additional Sessions Judge POCSO-01",
         "12 Sh. Atul Ahlawat - Special Judge, NDPS",
         "13 Ms. Meenu Kaushik - District Judge-03",
         "16 Dr. Pankaj Sharma - District Judge-02",
         "18 Sh. Syed Zishan Ali Warsi - Additional Sessions Judge-04",
         "21 Prashant Sharma - Additional Sessions Judge-03",
         "52 Sh. Dharmender Rana - District Judge-01",
         "53 Sh. Shirish Aggarwal - Presiding Officer MACT-01",
         "75 Ms. Sugandha Aggarwal - District Judge-04",
         "84 Sh. Amit Bansal - Additional Sessions Judge-02",
         "762 Sh. Pulastya Pramachala - District Judge (Commercial Courts)-01",
         "763 Sh. Bhupesh Kumar - District Judge (Commercial Courts)-02",
         "764 Ms. Deepali Sharma - District Judge (Commercial Courts)-03",
         "765 Sh. Saurabh Pratap Singh Laler - Additional Sessions Judge-05",
         "766 Ms. Shefali Barnala Tandon - Additional Sessions Judge-06",
         "767 Sh. Dhirendra Rana - Additional Sessions Judge-07",
         "768 Sh. Anubhav Jain - District Judge-05",
         "771 Sh. Sandeep Gupta - Additional Sessions Judge POCSO-02",
         "772 Ms. Sonam Singh - Additional Sessions Judge POCSO-03",
         "773 Sh. Abhilash Malhotra - Presiding Officer MACT-02",
         "4 Sh. Aridaman Singh Cheema - Judicial Magistrate First Class-03",
         "14 Sh. Animesh Kumar - Judicial Magistrate First Class-02",
         "17 Sh. Siddhant Sihag - Additional Chief Judicial Magistrate-02",
         "19 Sh. Mridul Gupta - Chief Judicial Magistrate",
         "20 Sh. Sahil Monga - Judicial Magistrate First Class-06",
         "32 Sh. Pranav Joshi - Additional Chief Judicial Magistrate-01",
         "38 Ms. Charan Salwan - Judicial Magistrate First Class-01",
         "39 Ms. Kavita Bist - Judicial Magistrate First Class (Mahila Court-01)",
         "67 Ms. Twinkle Chawla - Judicial Magistrate First Class-04",
         "68 Ms. Vijayshree Rathore - Judicial Magistrate First Class-05",
         "78 Sh. Snehil Sharma - Judicial Magistrate First Class (NI ACT)-01",
         "764 Sh. Ravi - Judicial Magistrate First Class-07",
         "765 Sh. Animesh Kumar - Judicial Magistrate First Class (Evening Court-01)",
         "766 Sh. Snehil Sharma - Judicial Magistrate First Class (Evening Court-02)",
         "767 Ms. Kavita Bist - Judicial Magistrate First Class (Evening Court-03)",
         "769 Ms. Tabassum Khan - Judicial Magistrate First Class (Mahila Court-02)",
         "770 Ms. Anjali Singh - Judicial Magistrate First Class (NI ACT)-03",
         "771 Ms. Vanshika Mehta - Judicial Magistrate First Class (NI ACT)-04",
         "772 Sh. Siddhant Kumar - Judicial Magistrate First Class (NI ACT)-05",
         "773 Ms. Akanksha Singh - Judicial Magistrate First Class (NI ACT)-02",
         "775 Ms. Shivangi Vyas - Judicial Magistrate First Class (NI ACT) Digital Court-01",
         "776 Sh. Shivam Gupta - Judicial Magistrate First Class (NI ACT) Digital Court-02",
         "777 Ms. Nishtha Mehtani - Judicial Magistrate First Class (NI ACT) Digital Court-03",
         "778 Sh. Ankit Garg - Judicial Magistrate First Class-08",
         "780 Ms. Vidushi Garg - Judicial Magistrate First Class (Digital Traffic Court)-01",
         "781 Sh. Ravi - Judicial Magistrate First Class Evening Court-04",
         "782 Ms. Tabassum Khan - Judicial Magistrate First Class Evening Court-05",
         "54 Ms. Shruti Chaudhary - Senior Civil Judge Cum Rent Controller",
         "56 Robinjeet Singh - JSCC cum ASCJ cum GJ",
         "58 Sh. Rupinder Singh Dhiman - ACJ-Cum-CCJ-Cum-ARC",
         "83 Sh. Vaibhav Pratap Singh - Civil Judge",
         "1 Illa Rawat - Principal Judge Family Court New Delhi PHC",
         "2 Sh. Devender Kumar Garg - Judge, Family Court, New Delhi, PHC"
      ]
   },
   "centraldelhi":{
      "Rouse Avenue Court Complex":[
         "1 Sh Dinesh Bhatt - Principal District and Sessions Judge cum Special Judge (PC Act) (CBI)",
         "2 Sh Gaurav Rao - Special Judge (PC Act) (CBI)",
         "3 Murari Prasad Singh - Special Judge (PC Act) (CBI)",
         "4 Sh. Hasan Anzar - Special Judge (PC Act) (CBI)",
         "5 Sh. Gagandeep Singh - Special Judge (PC Act) (CBI)",
         "6 MS. COLETTE RASHMI KUJUR - Special Judge (PC Act) (CBI)",
         "7 Manisha Khurana Kakkar - Special Judge (PC Act) (CBI)",
         "8 Ms. Chhavi Kapoor - Special Judge (PC Act) (CBI)",
         "9 Sh. Ashwani Kumar Sarpal - Special Judge (PC Act) (CBI)",
         "10 Sh. Dig Vinay Singh - Special Judge (PC Act) (CBI)",
         "11 Sh Sanjay Jindal - Special Judge (PC Act) (CBI)",
         "12 Sh. Sudhanshu Kaushik - Special Judge (PC Act) (CBI)",
         "13 Sh. Sanjay Khanagwal - Special Judge (PC Act) (CBI)",
         "14 Smita Garg - Special Judge (PC Act) (CBI)",
         "15 Rajesh Malik - Special Judge (PC Act) (CBI)",
         "16 Sh. Ajay Gupta - Special Judge (PC Act) (CBI)",
         "17 Satish Kumar - Special Judge (PC Act) (CBI)",
         "18 Ms. Vijeta Singh Rawat - Special Judge (PC Act) (CBI)",
         "19 Ms Jyoti Kler - Special Judge (PC Act) (CBI)",
         "20 Sh Atul Krishna Agrawal - Special Judge (PC Act) (CBI)",
         "21 Sh. Arun Sukhija - Special Judge (PC Act) (CBI)",
         "22 Sh. Shailender Malik - Special Judge (PC Act) (CBI)",
         "23 SUSHANT CHANGOTRA - Special Judge (PC Act) (CBI)",
         "24 SH DHEERAJ MOR - Special Judge (PC Act) (CBI) (Coal Block Cases)",
         "25 Vidya Prakash - Special Judge (PC Act) (ACB)",
         "26 Ruchi Aggarwal Asrani - Special Judge (PC Act) (ACB)",
         "27 Dr. Vishal Gogne - Special Judge (PC Act) (CBI)",
         "28 Sh. Jitendra Singh - Special Judge (PC Act) (CBI)",
         "29 Sh. Sanjay Bansal - Special Judge (PC Act) (CBI) (Coal Block Cases)",
         "1 T. PRIYADARSHINI - Chief Judicial Magistrate",
         "2 Sh. Paras Dalal - Addl. Chief Judicial Magistrate",
         "3 Sh. Mayank Goel - Addl. Chief Judicial Magistrate",
         "4 Ms. Neha Mittal - Addl. Chief Judicial Magistrate",
         "5 SH. ASHWANI PANWAR - Addl. Chief Judicial Magistrate",
         "6 Ms. Jyoti Maheshwari - Addl. Chief Judicial Magistrate",
         "7 Ms. Neetu Nagar - Addl. Chief Judicial Magistrate",
         "46 SH ASHOK KUMAR - Presiding Officer - Labour Court",
         "47 Manjusha Wadhwa - Presiding Off.-Ind. Trib",
         "53 Ms. Archana Bhalla - Presiding Officer - Labour Court",
         "107 Ms. Ritu Singh - Presiding Officer - Labour Court",
         "115 Sh Arun Kumar Garg - Presiding Officer - Labour Court",
         "444 Sh. Neeraj Gaur - Presiding Officer - Labour Court",
         "763 SHARAD GUPTA - Presiding Off.-Ind. Trib",
         "765 MS. CHETNA SINGH - Presiding Officer - Labour Court",
         "766 Ms Rekha - Presiding Officer - Labour Court",
         "767 Sh. Surender Mohit Singh - Presiding Officer - Labour Court",
         "768 Sh. Sujit Saurabh - Presiding Officer - Labour Court",
         "769 Sh. Arun Goel - Presiding Officer - Labour Court"
      ],
      "Tis Hazari Court Complex":[
         "9 SH. SACHIN SOOD - District Judge",
         "25 SHREYA ARORA MEHTA - ADDITIONAL SESSIONS JUDGE SFTC - 02",
         "32 Sh. Rakesh Kumar-IV - Additional Sessions Judge",
         "33 Virender Singh - SPECIAL JUDGE (NDPS)",
         "109 Sh. Rakesh Kumar Sharma - Special Judge",
         "122 Sh. Naresh kumar Laka - District Judge",
         "123 Pooja Aggarwal - Presiding Off.-MACT",
         "131 Ms. Ekta Gauba Mann - SPECIAL JUDGE (NDPS)",
         "160 SH. SANDEEP KUMAR SHARMA - District Judge",
         "215 SH. NEERAJ SHARMA - District Judge",
         "271 PRAYANK NAYAK - Additional Sessions Judge",
         "301 SH. VIRENDER KUMAR BANSAL - Principal District and Sessions Judge (HQs)",
         "314 Ms. Shilpi Jain - Additional Sessions Judge",
         "329 SH. ABHISHEK SRIVASTAVA - District Judge",
         "356 Ruchika Singla - Presiding Off.-MACT",
         "421 SHIVALI SHARMA - District Judge",
         "471 SH. ABHISHEK GOYAL - Additional Sessions Judge",
         "581 Ankur Jain - Additional Sessions Judge",
         "584 Sh. Rakesh Kumar Sharma - District Judge",
         "609 Mayuri Singh - District Judge",
         "784 Ms. Neelofer Abida perveen - DISTRICT JUDGE (COMMERCIAL COURT) - 01, CENTRAL, THC",
         "785 SH. RAJESH KUMAR GOEL - DISTRICT JUDGE (COMMERCIAL COURT) - 02, CENTRAL, THC",
         "786 DEVENDRA KUMAR SHARMA - DISTRICT JUDGE (COMMERCIAL COURT) - 03, CENTRAL, THC",
         "787 Sh. Anil Kumar Sisodia - DISTRICT JUDGE (COMMERCIAL COURT) - 04, CENTRAL, THC",
         "788 Sh. Manoj Kumar - DISTRICT JUDGE (COMMERCIAL COURT) - 05, CENTRAL, THC",
         "789 Sh. Ram Lal Meena - DISTRICT JUDGE (COMMERCIAL COURT) - 06, CENTRAL, THC",
         "790 Sh. Vinay Singhal - District Judge",
         "791 Bhupinder Singh - ADDITIONAL SESSIONS JUDGE - 05",
         "792 Sunil Chaudhary - Special Judge",
         "793 SH. JITEN MEHRA - District Judge",
         "794 Ms. Sonam Gupta - ADDITIONAL SESSIONS JUDGE FTSC POCSO-01",
         "795 Harjeet Singh Jaspal - Additional Sessions Judge",
         "796 Sh. Deepak Kumar-I - Additional Sessions Judge",
         "797 SUMEET ANAND - DISTRICT JUDGE - 11",
         "798 Sh. Mukesh Kumar Gupta - DISTRICT JUDGE (COMMERCIAL COURT) - 07, CENTRAL, THC",
         "799 SH. SANJEEV KUMAR MALHOTRA - DISTRICT JUDGE (COMMERCIAL COURT) - 08, CENTRAL, THC",
         "800 Sh. Deepak Garg - DISTRICT JUDGE (COMMERCIAL COURT) - 09 CENTRAL THC",
         "801 Sh. Ajay Pandey - DISTRICT JUDGE (COMMERCIAL COURT) - 10, CENTRAL, THC",
         "802 Sh. Surinder S. Rathi - DISTRICT JUDGE (COMMERCIAL COURT) - 11, CENTRAL, THC",
         "803 Sh. Sachin Gupta - Additional Sessions Judge (SC - POCSO)",
         "804 MS. PRIYANKA BHAGAT - Additional Sessions Judge (SC - RC)",
         "805 Ms. Ravinder Bedi - DISTRICT JUDGE (COMMERCIAL COURT) - 12. CENTRAL, THC",
         "806 Sh. M. K. Nagpal - DISTRICT JUDGE (COMMERCIAL COURT) - 13, CENTRAL, THC",
         "807 SH. VIRENDER KUMAR KHARTA - Additional Sessions Judge",
         "808 Sh. Joginder Prakash Nahar - Additional Sessions Judge",
         "809 MS. SHAGUN SHARMA - District Judge",
         "810 Tarun Yogesh - DISTRICT JUDGE - 13",
         "811 Anil Antil - DISTRICT JUDGE - 15",
         "812 PANKAJ ARORA - DISTRICT JUDGE - 16",
         "813 Chander Mohan - DISTRICT JUDGE - 14",
         "1 Nishat Bangarh - JUDICIAL MAGISTRATE FIRST CLASS - 01",
         "35 MS. SHAINA GOYAL - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 01",
         "37 MS. MANSI MALIK - ADDITIONAL CHIEF JUDICIAL MAGISTRATE - 02",
         "38 Harshita Mishra - CHIEF JUDICIAL MAGISTRATE",
         "42 MS. NEETU SHARMA - ADDITIONAL CHIEF JUDICIAL MAGISTRATE - 01",
         "286 SH. KARANBIR SINGH - JUDICIAL MAGISTRATE FIRST CLASS - 02",
         "353 Ms. Preeti Rajoria - JUDICIAL MAGISTRATE FIRST CLASS - 07",
         "405 SH. RANGAT GHIRRA - JUDICIAL MAGISTRATE FIRST CLASS - 04",
         "432 DR. RAJ KUMAR SINGH - JUDICIAL MAGISTRATE FIRST CLASS - 05",
         "438 MS. PREETI - JUDICIAL MAGISTRATE FIRST CLASS - 03",
         "475 Ms. Manya - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 02",
         "496 MS. RENU CHAUDHARY - ADDITIONAL CHIEF JUDICIAL MAGISTRATE (SPECIAL ACTS)",
         "508 Ms. Urvi Gupta - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 01",
         "511 Sh. Navdeep Gupta - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 02",
         "512 SH. PRANJAL GANGWAR - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 03",
         "552 Sh. Kartik Taparia - JUDICIAL MAGISTRATE FIRST CLASS - 06",
         "591 MS. SAYESHA CHADHA - JUDICIAL MAGISTRATE FIRST CLASS - 08",
         "597 MS. PAYAL SINGAL - JUDICIAL MAGISTRATE FIRST CLASS - 09",
         "778 DANVEER - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 04",
         "779 SH. KARANBIR SINGH - JUDICIAL MAGISTRATE FIRST CLASS (EVENING COURT 1)",
         "780 MS. POOJA YADAV - JUDICIAL MAGISTRATE FIRST CLASS EVENING COURT - 02",
         "781 MR. BHARAT AGGARWAL - JUDICIAL MAGISTRATE FIRST CLASS (EVENING COURT - 03)",
         "782 SH. ARVIND TOMAR - JUDICIAL MAGISTRATE FIRST CLASS (EVENING COURT - 04)",
         "785 MR. AJEET NARAYAN - Metropolitan Magistrate",
         "786 Kahkashan Jabin - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 04",
         "787 MS. POOJA YADAV - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 03",
         "789 SH. ARJUN KIRAR - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 05",
         "790 Ms.Ravisha Sidana - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 06",
         "791 SH. SAHIL MONGA - Metropolitan Magistrate",
         "795 Ms. Pooja Suhag - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 01",
         "796 SH. MAYANK AGGARWAL - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 02",
         "797 Shubhamjot Kaur Rakhra - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 03",
         "798 SH. CHANDRA BOSE - Presiding Officer, Special Court (NI Act)",
         "799 MS. DEEPIKA - JUDICIAL MAGISTRATE FIRST CLASS (DIGITAL TRAFFIC COURT)",
         "801 SH. ARVIND TOMAR - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 07",
         "802 SH. VAIBHAV GARG - JUDICIAL MAGISTRATE FIRST CLASS - 11",
         "803 MS. ARADHANA - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 04",
         "804 MS. GOWRI REGHUNATH - JUDICIAL MAGISTRATE FIRST CLASS - 10",
         "805 MS. RICHIKA TYAGI - JUDICIAL MAGISTRATE FIRST CLASS - 12",
         "806 Rashi Raheja - JUDICIAL MAGISTRATE FIRST CLASS - 13",
         "807 MR. AKASH SHARMA - CIVIL JUDGE EVENING COURT - 08",
         "808 Sh. Sunil Khatri - CIVIL JUDGE EVENING COURT - 09",
         "809 Mr. Milan Goel - CIVIL JUDGE EVENING COURT - 10",
         "810 SURBHI GUPTA ANAND - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 08",
         "811 MS. ARADHANA - JUDICIAL MAGISTRATE FIRST CLASS NI ACT - 09",
         "11 Ms. Dhanashree Deka - Senior Civil Judge Cum Rent Controller",
         "12 Sh. Gopal Krishan - JSCC-cum-Addl. SCJ-cum-Guardian Judge-01",
         "31 Mr. Milan Goel - Civil Judge",
         "179 SH. SAHIL GUPTA - Civil Judge",
         "275 Hala Quamar - CIVIL JUDGE - 01",
         "296 SH. AKSHAY PRAKASH - CIVIL JUDGE - 04",
         "326 Ms. Aayushi Saxena - Civil Judge",
         "327 MR. BHARAT AGGARWAL - ACJ-cum-CCJ-cum-ARC",
         "406 Sh. Sunil Khatri - CIVIL JUDGE - 06",
         "434 Sh. Gaurav Goyal - Additional Rent Controller-01",
         "477 Mr. Devanshu Sajlan - CCJ cum Addl. Rent Controller",
         "517 MR. AAKASH SHARMA - CIVIL JUDGE - 02",
         "590 MS. DIVYA GUPTA - ADDITIONAL RENT CONTROLLER - 02",
         "593 MS. SANA KHAN - CIVIL JUDGE - 05",
         "797 MR. UMESH KUMAR - JSCC-cum-Addl. SCJ-cum-Guardian Judge-02",
         "798 SH. ARVIND DEV - CIVIL JUDGE - 09",
         "586 Vineeta Goyal - Principal Judge, Family Court, Central Dist.",
         "784 Tyagita Singh - Judge, Family Court",
         "785 Naveen Kumar Kashyap - JUDGE FAMILY COURT - 02",
         "1 Amit Kumar - PRESIDING OFFICER - APPELLATE TRIBUNAL MCD"
      ]
   },
   "northdelhi":{
      "Rohini Court Complex":[
         "424 Ms Richa Manchanda - Presiding Off.-MACT",
         "426 Sh. Sidharth Mathur - District Judge",
         "431 Ms. Vandana - Additional Sessions Judge",
         "435 Sh. Viplav Dabas - ASJ/Spl.FTC North",
         "466 Sh. Prem Kumar Barthwal - Principal District and Sessions Judge, North",
         "496 Sh. Harvinder Singh Johal - ASJ/SPECIAL.JUDGE(NDPS)",
         "504 Sh. Sunil Kumar - Presiding Off.-MACT",
         "514 Sh. Amit Sahrawat - Additional Sessions Judge",
         "516 Sh. Jagmohan Singh - Additional Sessions Judge",
         "573 Sh. Sushil Kumar - Additional Sessions Judge",
         "576 Sh. Vikram Bali - District Judge",
         "757 Ms. Pooja Jain - Additional Sessions Judge",
         "758 Ms. Aanchal - District Judge",
         "760 Sh. Jagdish Kumar - District Judge (Commercial)",
         "761 Sh. Ravinder Singh II - District Judge",
         "762 Sh. Ajay Nagar - ASJ/Spl.FTC North",
         "763 Dr. Rakesh Kumar ll - District Judge (Commercial)",
         "434 Ms. Priyanka Rajpoot - Chief Judicial Magistrate",
         "436 Dr. Neha Kheria - Judicial Magistrate First Class",
         "443 Ms. Amardeep Kaur - Addl. Chief Judicial Magistrate",
         "460 MS. BHUJALI - Judicial Magistrate First Class",
         "462 Sh. Rohit Kumar - Judicial Magistrate First Class",
         "525 Ms. Sanya Dalal - Judicial Magistrate First Class (Mahila Court)-01",
         "528 Sh. Himanshu Sehloth - Judicial Magistrate First Class",
         "546 Ms. Garima Jindal - Judicial Magistrate First Class",
         "552 Ms. Bharti Beniwal - Judicial Magistrate First Class",
         "757 Dr. Neha Kheria - Judicial Magistrate First Class (Eve.Court-1)",
         "758 Ms. Renu - Civil Judge Evening Court-02",
         "759 Sh. Rohit Kumar - Judicial Magistrate First Class (Eve.Court-3)",
         "760 Ms. Jyoti Nain - Judicial Magistrate First Class",
         "761 Ms. Disha Singh - Judicial Magistrate First Class (Mahila Court)-02",
         "764 Sh. Gaurav Dahiya - Judicial Magistrate First Class",
         "765 Ms. Priyanka Gartan - Judicial Magistrate First Class",
         "766 Ms. Shreejee Abbot - Judicial Magistrate First Class",
         "767 Sh. Gaurav Dahiya - Judicial Magistrate First Class",
         "768 Ms. Bharti Beniwal - Judicial Magistrate First Class Eve. Court-4",
         "427 Sh. Ajay Singh Parihar - ACJ CUM ARC",
         "530 Sh. Nitish Kumar Sharma - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
         "534 Ms. Akriti Mahendru - Senior Civil Judge Cum Rent Controller",
         "566 Ms. Renu - Civil Judge",
         "556 Sh. Pankaj Gupta - Pr. Judge Family Court (North)",
         "558 Sh. Rajesh Kumar - Judge Family Court"
      ]
   },
   "southdelhi":{
      "Saket Court Complex":[
         "6 Sh. SAMAR VISHAL - Additional Sessions Judge-02",
         "8 Ms. Mona Tardi Kerketta - Additional Sessions Judge",
         "18 Sh. Gaurav Gupta - SPECIAL.JUDGE(NDPS)",
         "38 Ms. Niti Phutela - Additional Sessions Judge",
         "49 Sh. Gurvinder Pal Singh - Principal District and Sessions Judge",
         "56 MS. AMBIKA SINGH - District Judge - 01",
         "64 Sh. Vivek Kr. Gulia - Additional Sessions Judge",
         "67 Sh. Ravindra Kr. Pandey - Additional Sessions Judge",
         "75 Ms. Anjani Mahajan - Presiding Off.-MACT",
         "87 SH. MUNISH BANSAL - District Judge -03",
         "202 SH. ARUL VARMA - District Judge - 02",
         "205 SH. ABHITOSH PRATAP SINGH RATHORE - District Judge - 04",
         "768 Ms.Manika - Additional Sessions Judge",
         "770 Ms. Savita Rao - District Judge (Commercial Court) - 01",
         "771 Ms. Anuradha Shukla - District Judge (Commercial Court) - 02",
         "773 Mr. Ajay Garg - Additional Sessions Judge Cum FTC",
         "774 Sh. Ajay Kumar Jain - District Judge (Commercial Court) (Digital) 04",
         "775 Sh. Sandeep Yadav - District Judge (Commercial Court) 03",
         "776 Ms. Shunali Gupta - Additional Sessions Judge",
         "777 SH. HARGURVARINDER S. JAGGI - Additional Sessions Judge",
         "778 Sh.Purshotam Pathak - Additional Sessions Judge",
         "779 Sh. Pawan Kumar - Additional Sessions Judge",
         "781 SH. POORAN CHAND - District Judge -05",
         "782 Ms. NABEELA WALI - Additional Sessions Judge -SC-RC",
         "783 Sh. Dinesh Kumar - Additional Sessions Judge",
         "784 Mr.Sunil Beniwal - District Judge - 06",
         "785 Sh. Lokesh Kumar Sharma - District Judge (Commercial Court) 05",
         "10 Ms. Ankita Bhatia - Judicial Magistrate First Class (NI Act)-03",
         "17 Ms. Nidhi Singh - Judicial Magistrate First Class-03",
         "20 Ms. Niharika Kumar Sharma - Chief Judicial Magistrate",
         "23 Ms. Shikha Chahal - Judicial Magistrate First Class (Mahila Court)-01",
         "25 Sh. Chatinder Singh - Judicial Magistrate First Class-04",
         "27 MS. CHHAYA TYAGI - Judicial Magistrate First Class (Mahila Court)-02",
         "34 Ms. Radha Kulshreshtha - Judicial Magistrate First Class (NI Act)-01",
         "42 SH. BHANU PRATAP SINGH - Judicial Magistrate First Class-02",
         "45 Ms. ARIBA KHAN - Judicial Magistrate First Class (NI Act)-02",
         "46 MS. MEDHA ARYA - Additional Chief Judicial Magistrate",
         "54 Ms. Neetika Kapoor - Judicial Magistrate First Class (Mahila Court)-03",
         "81 SH. ASHISH KUMAR MEENA - Judicial Magistrate First Class-01",
         "767 Sh. Shiva Parashar - Judicial Magistrate First Class (NI Act)-04",
         "768 Ms. Jayanti Chander - Judicial Magistrate First Class - Evening Court 01",
         "771 Sh. Nitin Shah - Judicial Magistrate First Class (NI Act)-05",
         "772 MS. CHAKITA SRIVASTAVA - Judicial Magistrate First Class (Mahila Court)-04",
         "773 Ms. Norma Jain - Judicial Magistrate First Class (NI Act) Digital Court-01",
         "774 Ms. Pooja Kumari - Judicial Magistrate First Class (NI Act) Digital Court-02",
         "775 Ms. Anshul Agnihotri - Judicial Magistrate First Class (NI Act) Digital Court-03",
         "780 Ms. Nirmala Singh - Judicial Magistrate First Class-05",
         "781 SH. SUKHJEET SINGH - Judicial Magistrate First Class-06",
         "783 Ms. Archita Garg - Judicial Magistrate First Class (NI Act)-06",
         "784 Ms. Jayanti Chander - Judicial Magistrate First Class (NI Act)-07",
         "785 MR. AKSHAY SHARMA - Judicial Magistrate First Class (NI Act)-08",
         "786 MS. KAMALDEEP KAUR - Judicial Magistrate First Class (Digital Traffic Court)",
         "788 Ms. ARIBA KHAN - Judicial Magistrate First Class - Evening Court 02",
         "789 SH. SUKHJEET SINGH - Judicial Magistrate First Class - Evening Court 03",
         "790 MS. CHAKITA SRIVASTAVA - Judicial Magistrate First Class - Evening Court 04",
         "791 MR. AKSHAY SHARMA - Judicial Magistrate First Class - Evening Court 05",
         "792 Sidhant Krishan Singh - Judicial Magistrate First Class NI Act-09",
         "793 Ms. Pooja Kumari - Judicial Magistrate First Class NI Act-10",
         "794 Ms. Anshul Agnihotri - Judicial Magistrate First Class NI Act-11",
         "47 Sh. Ankit Mittal - Civil Judge",
         "55 MS. NEHA PRIYA - Senior Civil Judge Cum Rent Controller",
         "57 Mr. Vipul Sandwar - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
         "59 MS. SHILPI SINGH - Commercial Civil Judge CUM ARC CUM ADMIN-CJ",
         "767 Yashdeep Chahal - Civil Judge",
         "1 Sh. Sanjay Garg II - Principal Judge Family Court South District",
         "2 Sh. Sunil Gupta - Judge, Family Court",
         "3 Ms. Purva Sareen - Judge, Family Court"
      ]
   },
   "northeast":{
      "Karkardooma Court Complex":[
         "5 Sh. Puneet Pahwa - ASJ/SPECIAL.JUDGE(NDPS)",
         "45 Sh. Shankar Narayanan - Additional Sessions Judge",
         "413 Sh. Ashwani Kumar Sarpal - Principal District and Sessions Judge - North-East District",
         "423 Ms. Twinkle Wadhwa - Additional Sessions Judge",
         "429 Sh. Aashish Gupta - District Judge",
         "442 Sh. Praveen Singh - Additional Sessions Judge",
         "476 Mr. Devender Nain - Presiding Officer-MACT",
         "763 Sh. Gorakh Nath Pandey - District Judge (Commercial Court)",
         "764 Ms. Richa Parihar - Additional Sessions Judge",
         "765 Ms. Gomati Manocha - District Judge",
         "766 Sh. Babru Bhan - Additional Sessions Judge",
         "767 Sh. Ajay Gulati-II - Additional Sessions Judge",
         "768 Sh. Balwinder Singh - Additional Sessions Judge",
         "18 Sh. Pankaj Rai - Judicial Magistrate First Class",
         "35 Ms. Tanya Bamniyal - Chief Judicial Magistrate",
         "63 Sh. Anmol Nohria - Judicial Magistrate First Class",
         "460 Sh. Tushar Gupta - Addl. Chief Judicial Magistrate",
         "462 Ms. Neha Barupal - Judicial Magistrate First Class (Mahila Court)-01",
         "763 Ms. Shruti Saraswat - Judicial Magistrate First Class",
         "765 Sh. Aakash Mohan Singh - Judicial Magistrate First Class (NI Act) Digital Court",
         "766 Ms. Neha Garg - Judicial Magistrate First Class (Mahila Court)-02",
         "767 Ms. Isra Zaidi - Judicial Magistrate First Class",
         "768 Ms. Pranjali Prakash - Judicial Magistrate First Class (Digital Traffic Court)",
         "769 Ms. Neha Garg - Judicial Magistrate First Class Evening Court-4",
         "770 Ms. Nishtha Mehtani - Judicial Magistrate First Class NI Act",
         "67 Ms. Tania Singh - Senior Civil Judge",
         "72 Sh. Animesh Bhaskar Mani Tripathi - ACJ/CCJ/ARC",
         "104 Sh. Ajay Kumar Malik - Judge-Small Cause Court",
         "1 Ms. Hemani Malhotra - Principal Judge, Family Court, North East Distt",
         "2 Sh. Ajay Singh Shekhawat - Judge Family Court-01",
         "3 Sh. Chander Jit Singh - Judge, Family Court-02"
      ]
   },
   "southeastdelhi":{
      "Saket Court Complex":[
         "2 Ms. Charu Gupta - PO (MACT)-01",
         "3 Sh. Ankit Singla - Additional Sessions Judge FTC -02",
         "4 Sh. Vipin Kumar Rai - Additional Sessions Judge POCSO",
         "9 Dr. Tarun Sahrawat - Additional Sessions Judge",
         "10 Sh. Kuldeep Narayan - District Judge - 02",
         "11 Ms. Nivedita Anil Sharma - Principal District and Sessions Judge",
         "14 Sh. Rahul Bhatia - District Judge - 01",
         "19 Pritam Singh - District Judge - 04",
         "24 Sh. Anuj Aggarwal - Additional Sessions Judge",
         "62 Ms. Sheetal Chaudhary Pradhan - Additional Sessions Judge",
         "89 Sh. Sachin Mittal - District Judge - 03",
         "201 Ms. Prabh Deep Kaur - District Judge - 05",
         "204 Sh. Vishal Singh - Additional Sessions Judge",
         "206 Ms. Neha - District Judge - 06",
         "767 Sh. Anil Kumar Paswan - District Judge - 07",
         "768 Ms. Anu Aggarwal - Additional Sessions Judge",
         "771 Sh. Lal Singh - District Judge (Commercial Court)-01",
         "773 Sh. Lalit Kumar - District Judge (Commercial Court)-02",
         "774 Ms. Swati Sharma - Additional Sessions Judge FTSCPOCSO",
         "775 Ms. Nirja Bhatia - District Judge (Commercial Court) (Digital)-07",
         "776 Ms. Vrinda Kumari - District Judge (Commercial Court)-03",
         "777 Ms. Sunena Sharma - District Judge (Commercial Court)-04",
         "778 Ms. Neelam Singh - District Judge (Commercial Court)-05",
         "779 Dr. Neera Bharihoke - District Judge (Commercial Court)-06",
         "780 Ms. Shivani Chauhan - Additional Sessions Judge FTC-01",
         "781 Sh. Vinod Kumar Gautam - Additional Sessions Judge FTC -02",
         "782 Sh. Pranjal Aneja - Additional Sessions Judge (SC-RC)",
         "787 Sh. Vipin Kharb - Additional Sessions Judge",
         "790 Ms. Aditi Garg - PO (MACT)-02",
         "791 Ms. Geetanjali - Additional Sessions Judge Cum FTC",
         "792 Ms. Ankita Lal - Additional Sessions Judge (SC-POCSO)",
         "793 Ms. Veena Rani - District Judge (Commercial Court) -08",
         "5 Ms. Marilyn Joanna Khakha - Judicial Magistrate First Class (Mahila Court) - 03",
         "13 Ms. Seema Nirmal - Judicial Magistrate First Class - 09",
         "21 Sh. Raghav Sharma - Judicial Magistrate First Class - 06",
         "22 Dr. Nupur Gupta - Chief Judicial Magistrate",
         "26 Ms. Akansha Gautam - Judicial Magistrate First Class - 02",
         "30 Ms. Aditi Rao - Judicial Magistrate First Class - 07",
         "31 Dr. Aneeza Bishnoi - Judicial Magistrate First Class - 05",
         "32 Ms. Shivangi Vyas - Judicial Magistrate First Class (Mahila Court) - 01",
         "33 Ms. Aastha Sharma - Judicial Magistrate First Class (NI Act) - 03",
         "41 Ms. Garima Garg - Judicial Magistrate First Class (NI Act) - 01",
         "48 Sh. Vinod Joshi - Addl. Chief Judicial Magistrate",
         "52 Sh. Bhavaya Karhail - Judicial Magistrate First Class - 08",
         "61 Ms. Shruti Sharma-I - Judicial Magistrate First Class (NI Act) - 02",
         "68 Ms. Neha Saini - Judicial Magistrate First Class (Mahila Court) - 02",
         "83 Sh. Manuj Kaushal - Judicial Magistrate First Class - 03",
         "84 Ms. Devanshi Janmeja - Judicial Magistrate First Class - 04",
         "85 Sh. Rahul Jain - Judicial Magistrate First Class - 01",
         "207 Ms. Seema Meena - Judicial Magistrate First Class (NI Act) - 04",
         "767 Ms. Aditi Rao - Judicial Magistrate First Class (Evening Court-01)",
         "768 Sh. Ajeet Narayan - Judicial Magistrate First Class (Evening Court -02)",
         "771 Sh. Azad Sehrawat - Judicial Magistrate First Class - 10",
         "773 Ms. Chhavi Bansal - Judicial Magistrate First Class - 11",
         "777 Sh. Navdeep Gupta - Judicial Magistrate First Class (NI Act) Digital Court - 01",
         "778 Mr. Ajay Narwal - Judicial Magistrate First Class (NI Act) Digital Court - 02",
         "779 Sh. Prithvi Joshi - Judicial Magistrate First Class (NI Act) Digital Court - 03",
         "781 Ms. Deepika Thakran - Judicial Magistrate First Class - 12",
         "782 Ms. Shubhangi Srivastava - Judicial Magistrate First Class (NI Act) - 05",
         "783 Ms. Nandini Garg - Judicial Magistrate First Class (Digital Traffic Court)",
         "784 Ms. Aastha Sharma - Judicial Magistrate First Class Evening Court -03",
         "785 Ms. Seema Meena - Judicial Magistrate First Class Evening Court -04",
         "786 Ms. Shubhangi Srivastava - Judicial Magistrate First Class Evening Court -05",
         "787 Sh. Anurag Chhabra - Judicial Magistrate First Class NI Act - 06",
         "788 Sh. Mayank Aggarwal - Judicial Magistrate First Class NI Act - 07",
         "789 Ms. Surbhi Sharma - Judicial Magistrate First Class NI Act - 08",
         "790 Ms. Shivangi Vyas - Judicial Magistrate First Class (Mahila Court) - 01",
         "15 Ms. Tarunpreet Kaur - Commercial Civil Judge CUM ARC CUM ADMIN-CJ",
         "29 Sh. Ajeet Narayan - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
         "44 Sh. Yashu Khurana - Civil Judge",
         "50 Sh. Fahad Uddin - Senior Civil Judge Cum Rent Controller",
         "768 Ms. Poorva Mehra - Civil Judge",
         "769 Ms. Isha Thakur - Civil Judge",
         "2 Sh. Nikhil Chopra - Principal Judge, Family Court, South East Dist.",
         "3 Ms. Monika Saroha - Judge, Family Court",
         "4 Ms. Namrita Aggarwal - Judge, Family Court"
      ]
   },
   "westdelhi":{
      "Tiz Hazari Court Complex":[
         "22 Dr. Aditi Choudhary - Principal District and Sessions Judge",
         "138 Sh. Vineet Kumar - Additional Sessions Judge",
         "156 Sh. Satvir Singh Lamba - Special Judge",
         "158 SH. SHIV KUMAR - District Judge",
         "201 Sh. Dharmender Singh - District Judge",
         "234 Sh. Vijay Shankar - Additional Sessions Judge",
         "450 Sh. Mukesh Kumar - Presiding Off.-MACT",
         "452 Sh. Gopal Singh Chauhan - District Judge",
         "472 Sh. Divyang Thakur - Additional Sessions Judge",
         "476 MS. GUNJAN GUPTA - Presiding Off.-MACT",
         "541 DR. YADVENDER SINGH - Additional Sessions Judge",
         "558 Satyabrata Panda - Additional Sessions Judge (FTC)",
         "582 Dr. Saurabh Kulshreshtha - Additional Sessions Judge",
         "601 Sh. Arvind Bansal - District Judge",
         "604 SH. ANIL CHANDHEL - District Judge",
         "607 Goma Dabas Gupta - District Judge",
         "778 Sh. Nipun Awasthi - Additional Sessions Judge",
         "783 Ms. Shelly Arora - Additional Sessions Judge",
         "784 SH. SACHIN JAIN - Additional Sessions Judge",
         "789 Sh. Ashutosh Kumar - DISTRICT JUDGE (COMMERCIAL COURT) - 01, WEST, THC",
         "790 Preeti Aggarwal Gupta - DISTRICT JUDGE (COMMERCIAL COURT) - 02, WEST, THC",
         "791 Priya Mahendra - Additional Sessions Judge",
         "793 SH. MANOJ KR. SHARMA - District Judge",
         "794 Deepak kumar II - Additional Sessions Judge (FTC)",
         "795 Saloni Singh - Additional Sessions Judge",
         "796 Ms.Kadambari Awasthi - Additional Sessions Judge",
         "797 Ms. Babita Puniya - Additional Sessions Judge",
         "798 RAGHUBIR SINGH - DISTRICT JUDGE (COMMERCIAL COURT) - 03, WEST, THC",
         "799 Sh. Siddhartha Malik - Additional Sessions Judge",
         "800 Vishal Pahuja - ADDITIONAL SESSIONS JUDGE SC-RC - 01",
         "801 Pooja Talwar - Additional Sessions Judge (FTC)",
         "802 Ms. Saumya Chauhan - Additional Sessions Judge (FTC)",
         "803 SH. ANKIT MEHTA - Additional Sessions Judge",
         "804 Harish Kumar - DISTRICT JUDGE (COMMERCIAL COURT) - 04, WEST, THC",
         "805 Sh. Raj Kumar Tripathi - DISTRICT JUDGE (COMMERCIAL COURT) - 05, WEST, THC",
         "806 Sh. Naresh Kumar Malhotra - DISTRICT JUDGE (COMMERCIAL COURT) - 06, WEST, THC",
         "807 Mr.Rajinder Singh - Additional Sessions Judge",
         "808 Sh. Naveen Gupta - District Judge",
         "809 Vinod Kumar Meena - District Judge",
         "810 Susheel Bala Dagar - District Judge",
         "40 MS. SURABHI SETHI - Judicial Magistrate First Class (NI ACT) - 02",
         "145 MS. UDITA JAIN GARG - Additional Chief Judicial Magistrate",
         "178 Sh. Tanmay Batham - Judicial Magistrate First Class (NI ACT) - 03",
         "210 Mr. Gaurav Singal - Judicial Magistrate First Class - 06",
         "252 MS. DIVYASHREE RAINA - Judicial Magistrate First Class (Mahila Court) - 04",
         "367 Ms. Shivli Talwar - Judicial Magistrate First Class (Mahila Court) - 01",
         "467 Vasundhara Azad - Chief Judicial Magistrate",
         "468 SH. SHASHANK NANDAN BHAT - Judicial Magistrate First Class - 02",
         "469 Ms. KOMAL GARG - Judicial Magistrate First Class - 03",
         "480 Ankur Panghal - Judicial Magistrate First Class - 05",
         "499 Ms. Ritu Singh - Chief Judicial Magistrate",
         "514 Mr. Gaurav Ujjwal - Judicial Magistrate First Class (NI ACT) - 01",
         "516 Sh. Anshul Singhal - Judicial Magistrate First Class - 04",
         "519 Komal - Judicial Magistrate First Class - 01",
         "555 MS. Shruti Sharma-II - Judicial Magistrate First Class (Mahila Court) - 02",
         "557 Deepika Goyal Shokeen - Judicial Magistrate First Class (Mahila Court) - 03",
         "781 SH. SHASHANK NANDAN BHAT - Judicial Magistrate First Class Evening Court - 01",
         "782 Ms. KOMAL GARG - Judicial Magistrate First Class Evening Court - 02",
         "789 Ms. Disha Langan - Judicial Magistrate First Class (Mahila Court) - 05",
         "790 Sh. Deepak Kumar-I - Metropolitan Magistrate",
         "792 Poonam Singh - Judicial Magistrate First Class (NI ACT) - 04",
         "793 MR. ANKIT KARAN SINGH - Judicial Magistrate First Class - 08",
         "795 Sh. Vikas Madaan - Judicial Magistrate First Class - 07",
         "796 Abhay Choudhary - Judicial Magistrate First Class (NI ACT) Digital Court - 01",
         "797 Shivangi Mangla - Judicial Magistrate First Class (NI ACT) Digital Court - 02",
         "798 Atisha Jain - Judicial Magistrate First Class (Digital Traffic Court)",
         "799 MS. ANAMIKA - Judicial Magistrate First Class (Mahila Court) - 06",
         "800 Deshna Golechha - Judicial Magistrate First Class (NI ACT) Digital Court - 03",
         "801 Shraddha Srivastava - Judicial Magistrate First Class - 09",
         "802 Moksha Bains - Judicial Magistrate First Class - 11",
         "803 Ms. Aishwarya Singh Kashyap - Judicial Magistrate First Class - 10",
         "804 Sheetal Rani - Judicial Magistrate First Class - 12",
         "805 Sh. Lalit Kumar - Judge Evening Court - 05",
         "806 Sh. Kautuk Bhardwaj - Judge Evening Court - 06",
         "807 Shivangi Mangla - Judicial Magistrate First Class NI ACT - 05",
         "3 MS. NEHA PANDEY - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
         "118 Ishita Bhardwaj - Civil Judge",
         "125 Sh. Kautuk - Civil Judge",
         "178 MR. ANSHUL MEHTA - ACJ-cum-CCJ-cum-ARC",
         "252 MS. RICHA SHARMA - Senior Civil Judge Cum Rent Controller",
         "277 Sh. Lalit Kumar - Civil Judge - 02",
         "474 MS. ALKA SINGH - CCJ cum Addl. Rent Controller",
         "797 Sh. Vivek Kumar Agarwal - JSCC-cum-ASCJ-cum-Guardian Judge - 02",
         "798 MR. DEV SAROHA - Civil Judge - 04",
         "587 Sh. Vijay Kumar Dahiya - Principal Judge, Family Court, West Dist.",
         "588 Manish Gupta - Judge, Family Court",
         "785 Sh. Lovleen - Judge, Family Court"
      ]
   },
   "southwestdelhi":{
      "Dwarka Court Complex":[
         "422 Ms. Harleen Singh - Additional Sessions Judge",
         "424 Ms. Shilpi M. Jain - District Judge",
         "435 Ms. Rashmi Gupta - Additional Sessions Judge",
         "437 Sh. Harjyot Singh Bhalla - District Judge",
         "438 Sh. Rakesh Kumar Singh - Presiding Officer-MACT-01",
         "440 Ms. Vandana Jain - Additional Sessions Judge",
         "458 Ms. Bhavna Kalia - ASJ/SPECIAL.JUDGE(NDPS)",
         "464 Sh. Pawan Kumar Jain - Principal District and Sessions Judge",
         "467 Ms. Rajat Goyal - Additional Sessions Judge",
         "501 Ms. Shivali Bansal - Additional Sessions Judge",
         "515 Sh. Manoj Kumar II - District Judge",
         "518 Sh. Sumit Dalal - District Judge",
         "546 Ms. Richa Gusain Solanki - District Judge",
         "759 Mr. Raj Kumar - District Judge (Commercial Court)-01",
         "760 Sh. Sushil Anuj Tyagi - Additional Sessions Judge",
         "761 Sh. Sudeep Raj Saini - Presiding Officer-MACT-02",
         "762 Sh. Vaibhav Mehta - Additional Sessions Judge",
         "763 Sh. Santosh Kumar Singh - Additional Sessions Judge",
         "764 Sh. Anurag Dass - Additional Sessions Judge",
         "765 Ms. Gurmohina Kaur - Additional Sessions Judge",
         "766 Sh. Deepak Wason - Additional Sessions Judge",
         "767 Sh. Gautam Manan - District Judge (Commercial Court)-03",
         "768 Sh. Balwant Rai Bansal - District Judge (Commercial Court)-02",
         "769 Sh. Himanshu Raman Singh - Additional Sessions Judge",
         "770 Sh. Rohit Gulia - Additional Sessions Judge",
         "771 Sh. Rakesh Pandit - District Judge (Commercial Court)-04",
         "772 Ms. Manu Goel Kharb - ASJ/SPECIAL.JUDGE(NDPS)",
         "773 Ms. Mahima Rai Singh - Additional Sessions Judge",
         "400 Ms. Surbhi - Judicial Magistrate First Class",
         "421 Ms. Deepali Srivastava - Additional Chief Judicial Magistrate",
         "423 Ms. Pallavi Tyagi - Judicial Magistrate First Class",
         "428 Ms. Neelmani Sharma - Judicial Magistrate First Class",
         "433 Ms. Divya Singh - Judicial Magistrate First Class",
         "442 Sh. Harshal Negi - Judicial Magistrate First Class",
         "444 Dr. Priya Janghu - Judicial Magistrate First Class",
         "450 Ms. Divya Yadav - Judicial Magistrate First Class",
         "453 Ms. Apoorva Rana - Judicial Magistrate First Class",
         "454 Mr. Rahul Katare - Judicial Magistrate First Class",
         "460 Sh. Saurabh Goyal - Judicial Magistrate First Class",
         "496 Ms. Kritika Jain - Judicial Magistrate First Class",
         "497 Sh. Rishabh Kapoor - Judicial Magistrate First Class",
         "498 Ms. Surabhi Rastogi - Judicial Magistrate First Class",
         "514 Ms. Divya Arora - Judicial Magistrate First Class",
         "542 Mr. Rahul Katare - Judicial Magistrate First Class (Evening Court-1)",
         "543 Ms. Deepika Yadav - Judicial Magistrate First Class (Evening Court-2)",
         "544 Sh. Ajay Narwal - Judicial Magistrate First Class (Evening Court-3)",
         "545 Ms. Sonica Meena - Judicial Magistrate First Class (Evening Court-4)",
         "548 Ms. Deeksha Rao - Municipal Magistrate",
         "551 Ms. Samiksha Gupta - Chief Judicial Magistrate",
         "553 Ms. Sukriti Jha - Judicial Magistrate First Class (Evening Court-5)",
         "554 Ms. Divya Singh - Judicial Magistrate First Class (Evening Court-6)",
         "558 Ms. Shubhi Gupta - Judicial Magistrate First Class (Evening Court-7)",
         "559 Ms. Vinerjeet Kaur - Judicial Magistrate First Class (Evening Court-8)",
         "757 Ms. Kirandeep Kaur - Judicial Magistrate First Class",
         "758 Sh. Shiv Kumar - Judicial Magistrate First Class",
         "759 Ms. Vinerjeet Kaur - Judicial Magistrate First Class",
         "760 Ms. Shubhangi Aggarwal - Judicial Magistrate First Class",
         "761 Ms. Ashima Lakhanpall - Judicial Magistrate First Class",
         "763 Sh. Shubham Gupta - Judicial Magistrate First Class",
         "764 Ms. Sonica Meena - Judicial Magistrate First Class",
         "765 Sh. Anurag Chhabra - Judicial Magistrate First Class",
         "766 Sh. Kawal Singh - Judicial Magistrate First Class",
         "767 Ms. Surbhi Gupta Anand - Judicial Magistrate First Class",
         "768 Ms. Deepika Yadav - Judicial Magistrate First Class",
         "769 Sh. Anubhav Bijalwan - Judicial Magistrate First Class",
         "770 Ms. Shreya Singh - Judicial Magistrate First Class",
         "771 Ms. Nandini Sharma - Judicial Magistrate First Class",
         "772 Ms. Deeksha Sethi - Judicial Magistrate First Class",
         "773 Sh. Abhinav Ahlawat - Judicial Magistrate First Class",
         "774 Sh. Nidhish Kumar Meena - Judicial Magistrate First Class",
         "775 Ms. Shubhi Gupta - Judicial Magistrate First Class",
         "776 Sh. Harjot Singh Aujla - Judicial Magistrate First Class",
         "778 Sh. Nitesh Goel - Judicial Magistrate First Class",
         "785 Sh. Mayank Singhal - Judicial Magistrate First Class",
         "787 Ms. Bhawna Rattan - Judicial Magistrate First Class",
         "788 Sh. Amit Rana - Judicial Magistrate First Class",
         "790 Ms. Anuradha Sonker - Judicial Magistrate First Class",
         "791 Ms. Sukriti Jha - Judicial Magistrate First Class",
         "792 Ms. Parul Sharma - Judicial Magistrate First Class",
         "793 Ms. Divya Yadav - Judicial Magistrate First Class (Evening Court-9)",
         "425 Sh. Anubhav Sharma - Civil Judge",
         "439 Sh. Sukhman Sandhu - Administrative Civil Judge cum Addl. Rent Controller",
         "531 Ms. Tapasya Agarwal - Judge Incharge - SCJ cum RC",
         "532 Sh. Vaibhav Chaurasia - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
         "757 Sh. Sarthak Panwar - Civil Judge",
         "758 Sh. Suneet Anand - Civil Judge",
         "449 Sh. Pitamber Dutt - Principal Judge, Family Court",
         "503 Ms. Niyay Bindu - Judge, Family Court-01",
         "757 Ms. Navita Kumari Bagha - Additional Principal Judge",
         "1 Ms. Chitranshi Arora - Principal Magistrate"
      ]
   },
   "rohini":{
      "Rohini Court Complex":[
         "423 Ms. Rajani Ranga - Additional Sessions Judge",
         "425 Ms. Nisha Sahay Saxena - Principal District and Sessions Judge, North West",
         "430 Sh. Vikram - ADJ1(NW)/MACT",
         "432 Sh. Shivaji Anand - ASJ/SPECIAL.JUDGE(NDPS)",
         "439 Sh. Kapil Kumar - ASJ/FTC NW",
         "449 Ms. Deepika Singh - Presiding Off.-MACT",
         "499 Sh. Muneesh Garg - Additional Sessions Judge",
         "503 Ms. Kiran Gupta - District Judge (North-West)",
         "505 Sh. Ashish Aggarwal - District Judge",
         "515 Sh. Prashant Kumar - Additional Sessions Judge",
         "572 Ms. Jasjeet Kaur - Additional Sessions Judge",
         "575 Sh. Rakesh Kumar V - District Judge",
         "758 Sh. Devender Kumar Jangala - District Judge (Commercial) - 01",
         "759 Mr. Rajinder Kumar - Additional Sessions Judge",
         "760 Ms. Neeti Suri Mishra - ASJ/FTC NW",
         "761 Sh. Vinod Yadav - District Judge (Commercial) - 02",
         "450 Ms. Aishwarya Sharma - Judicial Magistrate First Class (Mahila Court)-01",
         "459 Ms. Upasana Satija - Chief Judicial Magistrate",
         "461 Ms. Reetika Jain - Judicial Magistrate First Class",
         "519 Ms. Anuradha Jindal - Addl. Chief Judicial Magistrate",
         "520 Ms. Ebbani Aggarwal - Judicial Magistrate First Class",
         "526 Sh. Abhinav Singh - Judicial Magistrate First Class",
         "527 Sh. Apoorv Bhardwaj - Judicial Magistrate First Class",
         "547 Ms. Nitika - Judicial Magistrate First Class",
         "551 Sh. Sanyam Jain - Judicial Magistrate First Class",
         "578 Ms. Neha Goel - Judicial Magistrate First Class (Mahila Court)-02",
         "758 Ms. Anuradha Jindal - Judicial Magistrate First Class (Evening Court-1)",
         "759 Sh. Sanyam Jain - Judicial Magistrate First Class (Evening Court-2)",
         "760 Ms. Reetika Jain - Judicial Magistrate First Class (Evening Court-3)",
         "762 Ms. Shagun - Judicial Magistrate First Class",
         "763 Sh. Gaurav Katariya - Judicial Magistrate First Class",
         "766 Sh. Kashish Bajaj - Judicial Magistrate First Class",
         "767 Ms. Shraddha Tripathi - Judicial Magistrate First Class",
         "769 Sh. Prithvi Joshi - Judicial Magistrate First Class Evening Court-4",
         "531 Sh. Mayank Mittal - Senior Civil Judge Cum Rent Controller",
         "532 Sh. Gaurav Sharma - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
         "533 Ms. Gita - ACJ CUM ARC",
         "582 Sh. Vaibhav Kumar - Civil Judge",
         "559 Sh. Umed Singh - Principal Judge, Family Courts (NW)",
         "561 Sh. Hem Raj - Judge Family Court"
      ]
   },
   "shahdara":{
      "Karkardooma Court Complex":[
         "108 Ms. Surabhi Sharma Vats - Additional Sessions Judge",
         "111 Ms. Charu Aggarwal - Additional Sessions Judge",
         "129 Sh. Munish Markan - Additional Sessions Judge - POCSO",
         "445 Sh. Vijay Kumar Jha - Presiding Officer-MACT",
         "464 Sh. Sanjay Sharma I - Principal District and Sessions Judge - Shahdara District",
         "468 Sh. Gaurav - District Judge",
         "477 Sh. Sameer Bajpai - Additional Sessions Judge",
         "762 Sh. Ankur Jain-II - District Judge",
         "764 Dr. Sumedh Kumar Sethi - Additional Sessions Judge",
         "765 Ms. Aakanksha Vyas - Additional Sessions Judge",
         "766 Sh. SUDESH KUMAR II - District Judge (Commercial Court)",
         "767 Ms. Kiran Bansal - District Judge (Commercial Court)-02",
         "768 Sh. Sanjay Sharma-II - District Judge (Commercial Court) 03",
         "769 Sh. Pawan Kumar Matto - District Judge (Commercial Court) 04",
         "770 Ms. Preeti Agarwala - Additional Sessions Judge",
         "771 Mohammad Ehtesham - District Judge",
         "772 Sh. Kumar Rajat - Additional Sessions Judge",
         "773 Ms. Manisha Tripathy - Additional Sessions Judge",
         "774 Sh. Harun Pratap - Presiding Officer-MACT",
         "775 Sh. Gajender Singh Nagar - Special Judge",
         "776 Sh. Deepanker Mohan - District Judge",
         "777 Sh. Harvinder Singh - Additional Sessions Judge",
         "23 Ms. Shipra Dhankar - Judicial Magistrate First Class (Mahila Court)-01",
         "74 Ms. Sanghmitra - Judicial Magistrate First Class",
         "455 Sh. Mohit Sharma - Chief Judicial Magistrate",
         "456 Ms. Deepakshi Rana - Judicial Magistrate First Class",
         "467 Kanika Agarwal - Judicial Magistrate First Class (Mahila Court)-02",
         "469 Sh. Manish Jain - Addl. Chief Judicial Magistrate",
         "762 Sh. Akhil Malik - Judicial Magistrate First Class",
         "763 Ms. Nidhi Bala - Judicial Magistrate First Class (Mahila Court)-03",
         "764 Sh. Udbhav Kumar Jain - Judicial Magistrate First Class",
         "765 Ms. Anushtha Srivastava - Judicial Magistrate First Class",
         "766 Ms. Arushi Parwal - Judicial Magistrate First Class",
         "767 Ms. Nishi Jindal - Judicial Magistrate First Class (NI Act) Digital Court",
         "770 Ms. Karuna - Judicial Magistrate First Class",
         "775 Shazadi Halima Sadiya - Judicial Magistrate First Class (Digital Traffic Court)",
         "776 Ms. Manisha Bhau - Judicial Magistrate First Class NI Act",
         "777 Sh. Rahul Saini - Judicial Magistrate First Class",
         "778 Sh. Vinod Kumar - Judicial Magistrate First Class (NI Act) Digital Court",
         "779 Sh. Udbhav Kumar Jain - Judicial Magistrate First Class-Evening Court-04",
         "20 Ms Pragati - Senior Civil Judge",
         "73 Ms. Arjinder Kaur - Judge-Small Cause Court",
         "428 Ms. Charu Asiwal - ACJ/CCJ/ARC",
         "762 Sh. Jitender - Civil Judge-01",
         "763 Sh. Varun Chandra - Civil Judge-02",
         "765 Padma Ladol - Civil Judge-03",
         "480 Sh. Sanjeev Aggarwal - Principal Judge, Family Court, Shahdara",
         "762 Ms. Savitri - Judge, Family Court-02",
         "763 Sh. Sumit Dass - Judge Family Court-01",
         "764 Ms. Riya Guha - Judge Family Court-03",
         "1 Ms. Akanksha Garg - Principal Magistrate JJB-VI"
      ]
   }
}
module.exports = {delhiCourts};