const delhiCourtFlatList = [
  "eastdelhi;Karkardooma Court Complex;1 Ms. Sukhvinder Kaur - Principal District and Sessions Judge, East District",
  "eastdelhi;Karkardooma Court Complex;4 Ms. APARNA SWAMI - Presiding Off.-MACT",
  "eastdelhi;Karkardooma Court Complex;17 Sh. Ramesh Kumar-II - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;49 Sh. Ravinder Singh-I - District Judge",
  "eastdelhi;Karkardooma Court Complex;419 Sh. Hem Singh - District Judge",
  "eastdelhi;Karkardooma Court Complex;463 Ms. Manu Vedwan - ASJ/SPECIAL.JUDGE(NDPS)",
  "eastdelhi;Karkardooma Court Complex;466 Ms. Swati Katiyar - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;474 Sh. Subhash Kumar Mishra - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;482 Ms. Shuchi Laler - District Judge",
  "eastdelhi;Karkardooma Court Complex;763 Sh. Ashish Rastogi - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;764 Ms. Vasundhra Chhaunkar - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;765 Sh. Akash Jain - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;767 Sh. Devender Kumar - District Judge (Commercial Court)",
  "eastdelhi;Karkardooma Court Complex;768 Ms. Vidhi Gupta Anand - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;769 Ms. Ruby Alka Gupta - District Judge (Commercial Court) 02",
  "eastdelhi;Karkardooma Court Complex;770 Sh. Jitendra Pratap Singh - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;771 Ms. Snigdha Sarvaria - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;772 Sh. Rakesh Kumar Rampuri - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;774 Sh. Sonu Agnihotri - District Judge",
  "eastdelhi;Karkardooma Court Complex;776 Sh. Vikas Garg - District Judge",
  "eastdelhi;Karkardooma Court Complex;777 Sh. Somitra Kumar - District Judge",
  "eastdelhi;Karkardooma Court Complex;778 Sh. Anurag Thakur - Additional Sessions Judge",
  "eastdelhi;Karkardooma Court Complex;12 Sh. Rinku Jain - Addl. Chief Judicial Magistrate",
  "eastdelhi;Karkardooma Court Complex;16 Ms. Prigya Gupta - Chief Judicial Magistrate",
  "eastdelhi;Karkardooma Court Complex;24 Sh. Pritu Raj - Judicial Magistrate First Class",
  "eastdelhi;Karkardooma Court Complex;34 Ms. Sonam Singh II - Judicial Magistrate First Class (Mahila Court)-01",
  "eastdelhi;Karkardooma Court Complex;435 Sh. Satendra Pal Singh - Judicial Magistrate First Class",
  "eastdelhi;Karkardooma Court Complex;439 Sh. Sachin - Judicial Magistrate First Class",
  "eastdelhi;Karkardooma Court Complex;446 Sh. Divyam Lila - Municipal Magistrate",
  "eastdelhi;Karkardooma Court Complex;451 Sh. Ankit Solanki - Judicial Magistrate First Class NI Act-01",
  "eastdelhi;Karkardooma Court Complex;461 Ms. Ritika Kansal - Judicial Magistrate First Class (Mahila Court)-02",
  "eastdelhi;Karkardooma Court Complex;471 Ms. Prerna Rai - Judicial Magistrate First Class",
  "eastdelhi;Karkardooma Court Complex;762 Sh. P. Bhargav Rao - Judicial Magistrate First Class",
  "eastdelhi;Karkardooma Court Complex;763 Sh. Sidhant Krishan Singh - Judicial Magistrate First Class (NI Act) Digital Court",
  "eastdelhi;Karkardooma Court Complex;764 Sh. Kunal Soni - Judicial Magistrate First Class (Digital Traffic Court)",
  "eastdelhi;Karkardooma Court Complex;766 Ms. Sanya Singh - Judicial Magistrate First Class",
  "eastdelhi;Karkardooma Court Complex;767 Sh. Pritu Raj - Judicial Magistrate First Class Evening Court-4",
  "eastdelhi;Karkardooma Court Complex;768 Ms. Shraddha Tripathi - Judicial Magistrate First Class NI Act-02",
  "eastdelhi;Karkardooma Court Complex;63 Sh. Vivek Beniwal - Senior Civil Judge",
  "eastdelhi;Karkardooma Court Complex;66 Sh. Vinik Jain - ACJ/CCJ/ARC",
  "eastdelhi;Karkardooma Court Complex;76 Dr. Saema Jain - Judge-Small Cause Court",
  "eastdelhi;Karkardooma Court Complex;762 Sh. Ayush Sharma - Civil Judge",
  "eastdelhi;Karkardooma Court Complex;1 Sh. Manish Khurana - Judge, Family Court -01 , East Distt.",
  "eastdelhi;Karkardooma Court Complex;2 Sh. Sanjeev Kumar Aggarwal - Principal Judge, Family Court, East Dist.",
  "eastdelhi;Karkardooma Court Complex;3 Sh. Pawan Singh Rajawat - Judge Family Court 02",
  "eastdelhi;Karkardooma Court Complex;1 Sh. Sahil Khurmi - Principal Magistrate JJB-IV",
  "newdelhi;Patiala House Court Complex;1 Ms. Anju Bajaj Chandna - Principal District and Sessions Judge",
  "newdelhi;Patiala House Court Complex;10 Ms. Deepti Devesh - Additional Sessions Judge (SFTC)",
  "newdelhi;Patiala House Court Complex;11 Ms. Ruby Neeraj Kumar - Additional Sessions Judge POCSO-01",
  "newdelhi;Patiala House Court Complex;12 Sh. Atul Ahlawat - Special Judge, NDPS",
  "newdelhi;Patiala House Court Complex;13 Ms. Meenu Kaushik - District Judge-03",
  "newdelhi;Patiala House Court Complex;16 Dr. Pankaj Sharma - District Judge-02",
  "newdelhi;Patiala House Court Complex;18 Sh. Syed Zishan Ali Warsi - Additional Sessions Judge-04",
  "newdelhi;Patiala House Court Complex;21 Prashant Sharma - Additional Sessions Judge-03",
  "newdelhi;Patiala House Court Complex;52 Sh. Dharmender Rana - District Judge-01",
  "newdelhi;Patiala House Court Complex;53 Sh. Shirish Aggarwal - Presiding Officer MACT-01",
  "newdelhi;Patiala House Court Complex;75 Ms. Sugandha Aggarwal - District Judge-04",
  "newdelhi;Patiala House Court Complex;84 Sh. Amit Bansal - Additional Sessions Judge-02",
  "newdelhi;Patiala House Court Complex;762 Sh. Pulastya Pramachala - District Judge (Commercial Courts)-01",
  "newdelhi;Patiala House Court Complex;763 Sh. Bhupesh Kumar - District Judge (Commercial Courts)-02",
  "newdelhi;Patiala House Court Complex;764 Ms. Deepali Sharma - District Judge (Commercial Courts)-03",
  "newdelhi;Patiala House Court Complex;765 Sh. Saurabh Pratap Singh Laler - Additional Sessions Judge-05",
  "newdelhi;Patiala House Court Complex;766 Ms. Shefali Barnala Tandon - Additional Sessions Judge-06",
  "newdelhi;Patiala House Court Complex;767 Sh. Dhirendra Rana - Additional Sessions Judge-07",
  "newdelhi;Patiala House Court Complex;768 Sh. Anubhav Jain - District Judge-05",
  "newdelhi;Patiala House Court Complex;771 Sh. Sandeep Gupta - Additional Sessions Judge POCSO-02",
  "newdelhi;Patiala House Court Complex;772 Ms. Sonam Singh - Additional Sessions Judge POCSO-03",
  "newdelhi;Patiala House Court Complex;773 Sh. Abhilash Malhotra - Presiding Officer MACT-02",
  "newdelhi;Patiala House Court Complex;4 Sh. Aridaman Singh Cheema - Judicial Magistrate First Class-03",
  "newdelhi;Patiala House Court Complex;14 Sh. Animesh Kumar - Judicial Magistrate First Class-02",
  "newdelhi;Patiala House Court Complex;17 Sh. Siddhant Sihag - Additional Chief Judicial Magistrate-02",
  "newdelhi;Patiala House Court Complex;19 Sh. Mridul Gupta - Chief Judicial Magistrate",
  "newdelhi;Patiala House Court Complex;20 Sh. Sahil Monga - Judicial Magistrate First Class-06",
  "newdelhi;Patiala House Court Complex;32 Sh. Pranav Joshi - Additional Chief Judicial Magistrate-01",
  "newdelhi;Patiala House Court Complex;38 Ms. Charan Salwan - Judicial Magistrate First Class-01",
  "newdelhi;Patiala House Court Complex;39 Ms. Kavita Bist - Judicial Magistrate First Class (Mahila Court-01)",
  "newdelhi;Patiala House Court Complex;67 Ms. Twinkle Chawla - Judicial Magistrate First Class-04",
  "newdelhi;Patiala House Court Complex;68 Ms. Vijayshree Rathore - Judicial Magistrate First Class-05",
  "newdelhi;Patiala House Court Complex;78 Sh. Snehil Sharma - Judicial Magistrate First Class (NI ACT)-01",
  "newdelhi;Patiala House Court Complex;764 Sh. Ravi - Judicial Magistrate First Class-07",
  "newdelhi;Patiala House Court Complex;765 Sh. Animesh Kumar - Judicial Magistrate First Class (Evening Court-01)",
  "newdelhi;Patiala House Court Complex;766 Sh. Snehil Sharma - Judicial Magistrate First Class (Evening Court-02)",
  "newdelhi;Patiala House Court Complex;767 Ms. Kavita Bist - Judicial Magistrate First Class (Evening Court-03)",
  "newdelhi;Patiala House Court Complex;769 Ms. Tabassum Khan - Judicial Magistrate First Class (Mahila Court-02)",
  "newdelhi;Patiala House Court Complex;770 Ms. Anjali Singh - Judicial Magistrate First Class (NI ACT)-03",
  "newdelhi;Patiala House Court Complex;771 Ms. Vanshika Mehta - Judicial Magistrate First Class (NI ACT)-04",
  "newdelhi;Patiala House Court Complex;772 Sh. Siddhant Kumar - Judicial Magistrate First Class (NI ACT)-05",
  "newdelhi;Patiala House Court Complex;773 Ms. Akanksha Singh - Judicial Magistrate First Class (NI ACT)-02",
  "newdelhi;Patiala House Court Complex;775 Ms. Shivangi Vyas - Judicial Magistrate First Class (NI ACT) Digital Court-01",
  "newdelhi;Patiala House Court Complex;776 Sh. Shivam Gupta - Judicial Magistrate First Class (NI ACT) Digital Court-02",
  "newdelhi;Patiala House Court Complex;777 Ms. Nishtha Mehtani - Judicial Magistrate First Class (NI ACT) Digital Court-03",
  "newdelhi;Patiala House Court Complex;778 Sh. Ankit Garg - Judicial Magistrate First Class-08",
  "newdelhi;Patiala House Court Complex;780 Ms. Vidushi Garg - Judicial Magistrate First Class (Digital Traffic Court)-01",
  "newdelhi;Patiala House Court Complex;781 Sh. Ravi - Judicial Magistrate First Class Evening Court-04",
  "newdelhi;Patiala House Court Complex;782 Ms. Tabassum Khan - Judicial Magistrate First Class Evening Court-05",
  "newdelhi;Patiala House Court Complex;54 Ms. Shruti Chaudhary - Senior Civil Judge Cum Rent Controller",
  "newdelhi;Patiala House Court Complex;56 Robinjeet Singh - JSCC cum ASCJ cum GJ",
  "newdelhi;Patiala House Court Complex;58 Sh. Rupinder Singh Dhiman - ACJ-Cum-CCJ-Cum-ARC",
  "newdelhi;Patiala House Court Complex;83 Sh. Vaibhav Pratap Singh - Civil Judge",
  "newdelhi;Patiala House Court Complex;1 Illa Rawat - Principal Judge Family Court New Delhi PHC",
  "newdelhi;Patiala House Court Complex;2 Sh. Devender Kumar Garg - Judge, Family Court, New Delhi, PHC",
  "centraldelhi;Rouse Avenue Court Complex;1 Sh Dinesh Bhatt - Principal District and Sessions Judge cum Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;2 Sh Gaurav Rao - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;3 Murari Prasad Singh - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;4 Sh. Hasan Anzar - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;5 Sh. Gagandeep Singh - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;6 MS. COLETTE RASHMI KUJUR - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;7 Manisha Khurana Kakkar - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;8 Ms. Chhavi Kapoor - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;9 Sh. Ashwani Kumar Sarpal - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;10 Sh. Dig Vinay Singh - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;11 Sh Sanjay Jindal - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;12 Sh. Sudhanshu Kaushik - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;13 Sh. Sanjay Khanagwal - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;14 Smita Garg - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;15 Rajesh Malik - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;16 Sh. Ajay Gupta - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;17 Satish Kumar - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;18 Ms. Vijeta Singh Rawat - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;19 Ms Jyoti Kler - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;20 Sh Atul Krishna Agrawal - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;21 Sh. Arun Sukhija - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;22 Sh. Shailender Malik - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;23 SUSHANT CHANGOTRA - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;24 SH DHEERAJ MOR - Special Judge (PC Act) (CBI) (Coal Block Cases)",
  "centraldelhi;Rouse Avenue Court Complex;25 Vidya Prakash - Special Judge (PC Act) (ACB)",
  "centraldelhi;Rouse Avenue Court Complex;26 Ruchi Aggarwal Asrani - Special Judge (PC Act) (ACB)",
  "centraldelhi;Rouse Avenue Court Complex;27 Dr. Vishal Gogne - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;28 Sh. Jitendra Singh - Special Judge (PC Act) (CBI)",
  "centraldelhi;Rouse Avenue Court Complex;29 Sh. Sanjay Bansal - Special Judge (PC Act) (CBI) (Coal Block Cases)",
  "centraldelhi;Rouse Avenue Court Complex;1 T. PRIYADARSHINI - Chief Judicial Magistrate",
  "centraldelhi;Rouse Avenue Court Complex;2 Sh. Paras Dalal - Addl. Chief Judicial Magistrate",
  "centraldelhi;Rouse Avenue Court Complex;3 Sh. Mayank Goel - Addl. Chief Judicial Magistrate",
  "centraldelhi;Rouse Avenue Court Complex;4 Ms. Neha Mittal - Addl. Chief Judicial Magistrate",
  "centraldelhi;Rouse Avenue Court Complex;5 SH. ASHWANI PANWAR - Addl. Chief Judicial Magistrate",
  "centraldelhi;Rouse Avenue Court Complex;6 Ms. Jyoti Maheshwari - Addl. Chief Judicial Magistrate",
  "centraldelhi;Rouse Avenue Court Complex;7 Ms. Neetu Nagar - Addl. Chief Judicial Magistrate",
  "centraldelhi;Rouse Avenue Court Complex;46 SH ASHOK KUMAR - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;47 Manjusha Wadhwa - Presiding Off.-Ind. Trib",
  "centraldelhi;Rouse Avenue Court Complex;53 Ms. Archana Bhalla - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;107 Ms. Ritu Singh - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;115 Sh Arun Kumar Garg - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;444 Sh. Neeraj Gaur - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;763 SHARAD GUPTA - Presiding Off.-Ind. Trib",
  "centraldelhi;Rouse Avenue Court Complex;765 MS. CHETNA SINGH - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;766 Ms Rekha - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;767 Sh. Surender Mohit Singh - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;768 Sh. Sujit Saurabh - Presiding Officer - Labour Court",
  "centraldelhi;Rouse Avenue Court Complex;769 Sh. Arun Goel - Presiding Officer - Labour Court",
  "centraldelhi;Tis Hazari Court Complex;9 SH. SACHIN SOOD - District Judge",
  "centraldelhi;Tis Hazari Court Complex;25 SHREYA ARORA MEHTA - ADDITIONAL SESSIONS JUDGE SFTC - 02",
  "centraldelhi;Tis Hazari Court Complex;32 Sh. Rakesh Kumar-IV - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;33 Virender Singh - SPECIAL JUDGE (NDPS)",
  "centraldelhi;Tis Hazari Court Complex;109 Sh. Rakesh Kumar Sharma - Special Judge",
  "centraldelhi;Tis Hazari Court Complex;122 Sh. Naresh kumar Laka - District Judge",
  "centraldelhi;Tis Hazari Court Complex;123 Pooja Aggarwal - Presiding Off.-MACT",
  "centraldelhi;Tis Hazari Court Complex;131 Ms. Ekta Gauba Mann - SPECIAL JUDGE (NDPS)",
  "centraldelhi;Tis Hazari Court Complex;160 SH. SANDEEP KUMAR SHARMA - District Judge",
  "centraldelhi;Tis Hazari Court Complex;215 SH. NEERAJ SHARMA - District Judge",
  "centraldelhi;Tis Hazari Court Complex;271 PRAYANK NAYAK - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;301 SH. VIRENDER KUMAR BANSAL - Principal District and Sessions Judge (HQs)",
  "centraldelhi;Tis Hazari Court Complex;314 Ms. Shilpi Jain - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;329 SH. ABHISHEK SRIVASTAVA - District Judge",
  "centraldelhi;Tis Hazari Court Complex;356 Ruchika Singla - Presiding Off.-MACT",
  "centraldelhi;Tis Hazari Court Complex;421 SHIVALI SHARMA - District Judge",
  "centraldelhi;Tis Hazari Court Complex;471 SH. ABHISHEK GOYAL - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;581 Ankur Jain - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;584 Sh. Rakesh Kumar Sharma - District Judge",
  "centraldelhi;Tis Hazari Court Complex;609 Mayuri Singh - District Judge",
  "centraldelhi;Tis Hazari Court Complex;784 Ms. Neelofer Abida perveen - DISTRICT JUDGE (COMMERCIAL COURT) - 01, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;785 SH. RAJESH KUMAR GOEL - DISTRICT JUDGE (COMMERCIAL COURT) - 02, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;786 DEVENDRA KUMAR SHARMA - DISTRICT JUDGE (COMMERCIAL COURT) - 03, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;787 Sh. Anil Kumar Sisodia - DISTRICT JUDGE (COMMERCIAL COURT) - 04, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;788 Sh. Manoj Kumar - DISTRICT JUDGE (COMMERCIAL COURT) - 05, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;789 Sh. Ram Lal Meena - DISTRICT JUDGE (COMMERCIAL COURT) - 06, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;790 Sh. Vinay Singhal - District Judge",
  "centraldelhi;Tis Hazari Court Complex;791 Bhupinder Singh - ADDITIONAL SESSIONS JUDGE - 05",
  "centraldelhi;Tis Hazari Court Complex;792 Sunil Chaudhary - Special Judge",
  "centraldelhi;Tis Hazari Court Complex;793 SH. JITEN MEHRA - District Judge",
  "centraldelhi;Tis Hazari Court Complex;794 Ms. Sonam Gupta - ADDITIONAL SESSIONS JUDGE FTSC POCSO-01",
  "centraldelhi;Tis Hazari Court Complex;795 Harjeet Singh Jaspal - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;796 Sh. Deepak Kumar-I - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;797 SUMEET ANAND - DISTRICT JUDGE - 11",
  "centraldelhi;Tis Hazari Court Complex;798 Sh. Mukesh Kumar Gupta - DISTRICT JUDGE (COMMERCIAL COURT) - 07, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;799 SH. SANJEEV KUMAR MALHOTRA - DISTRICT JUDGE (COMMERCIAL COURT) - 08, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;800 Sh. Deepak Garg - DISTRICT JUDGE (COMMERCIAL COURT) - 09 CENTRAL THC",
  "centraldelhi;Tis Hazari Court Complex;801 Sh. Ajay Pandey - DISTRICT JUDGE (COMMERCIAL COURT) - 10, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;802 Sh. Surinder S. Rathi - DISTRICT JUDGE (COMMERCIAL COURT) - 11, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;803 Sh. Sachin Gupta - Additional Sessions Judge (SC - POCSO)",
  "centraldelhi;Tis Hazari Court Complex;804 MS. PRIYANKA BHAGAT - Additional Sessions Judge (SC - RC)",
  "centraldelhi;Tis Hazari Court Complex;805 Ms. Ravinder Bedi - DISTRICT JUDGE (COMMERCIAL COURT) - 12. CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;806 Sh. M. K. Nagpal - DISTRICT JUDGE (COMMERCIAL COURT) - 13, CENTRAL, THC",
  "centraldelhi;Tis Hazari Court Complex;807 SH. VIRENDER KUMAR KHARTA - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;808 Sh. Joginder Prakash Nahar - Additional Sessions Judge",
  "centraldelhi;Tis Hazari Court Complex;809 MS. SHAGUN SHARMA - District Judge",
  "centraldelhi;Tis Hazari Court Complex;810 Tarun Yogesh - DISTRICT JUDGE - 13",
  "centraldelhi;Tis Hazari Court Complex;811 Anil Antil - DISTRICT JUDGE - 15",
  "centraldelhi;Tis Hazari Court Complex;812 PANKAJ ARORA - DISTRICT JUDGE - 16",
  "centraldelhi;Tis Hazari Court Complex;813 Chander Mohan - DISTRICT JUDGE - 14",
  "centraldelhi;Tis Hazari Court Complex;1 Nishat Bangarh - JUDICIAL MAGISTRATE FIRST CLASS - 01",
  "centraldelhi;Tis Hazari Court Complex;35 MS. SHAINA GOYAL - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 01",
  "centraldelhi;Tis Hazari Court Complex;37 MS. MANSI MALIK - ADDITIONAL CHIEF JUDICIAL MAGISTRATE - 02",
  "centraldelhi;Tis Hazari Court Complex;38 Harshita Mishra - CHIEF JUDICIAL MAGISTRATE",
  "centraldelhi;Tis Hazari Court Complex;42 MS. NEETU SHARMA - ADDITIONAL CHIEF JUDICIAL MAGISTRATE - 01",
  "centraldelhi;Tis Hazari Court Complex;286 SH. KARANBIR SINGH - JUDICIAL MAGISTRATE FIRST CLASS - 02",
  "centraldelhi;Tis Hazari Court Complex;353 Ms. Preeti Rajoria - JUDICIAL MAGISTRATE FIRST CLASS - 07",
  "centraldelhi;Tis Hazari Court Complex;405 SH. RANGAT GHIRRA - JUDICIAL MAGISTRATE FIRST CLASS - 04",
  "centraldelhi;Tis Hazari Court Complex;432 DR. RAJ KUMAR SINGH - JUDICIAL MAGISTRATE FIRST CLASS - 05",
  "centraldelhi;Tis Hazari Court Complex;438 MS. PREETI - JUDICIAL MAGISTRATE FIRST CLASS - 03",
  "centraldelhi;Tis Hazari Court Complex;475 Ms. Manya - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 02",
  "centraldelhi;Tis Hazari Court Complex;496 MS. RENU CHAUDHARY - ADDITIONAL CHIEF JUDICIAL MAGISTRATE (SPECIAL ACTS)",
  "centraldelhi;Tis Hazari Court Complex;508 Ms. Urvi Gupta - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 01",
  "centraldelhi;Tis Hazari Court Complex;511 Sh. Navdeep Gupta - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 02",
  "centraldelhi;Tis Hazari Court Complex;512 SH. PRANJAL GANGWAR - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 03",
  "centraldelhi;Tis Hazari Court Complex;552 Sh. Kartik Taparia - JUDICIAL MAGISTRATE FIRST CLASS - 06",
  "centraldelhi;Tis Hazari Court Complex;591 MS. SAYESHA CHADHA - JUDICIAL MAGISTRATE FIRST CLASS - 08",
  "centraldelhi;Tis Hazari Court Complex;597 MS. PAYAL SINGAL - JUDICIAL MAGISTRATE FIRST CLASS - 09",
  "centraldelhi;Tis Hazari Court Complex;778 DANVEER - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 04",
  "centraldelhi;Tis Hazari Court Complex;779 SH. KARANBIR SINGH - JUDICIAL MAGISTRATE FIRST CLASS (EVENING COURT 1)",
  "centraldelhi;Tis Hazari Court Complex;780 MS. POOJA YADAV - JUDICIAL MAGISTRATE FIRST CLASS EVENING COURT - 02",
  "centraldelhi;Tis Hazari Court Complex;781 MR. BHARAT AGGARWAL - JUDICIAL MAGISTRATE FIRST CLASS (EVENING COURT - 03)",
  "centraldelhi;Tis Hazari Court Complex;782 SH. ARVIND TOMAR - JUDICIAL MAGISTRATE FIRST CLASS (EVENING COURT - 04)",
  "centraldelhi;Tis Hazari Court Complex;785 MR. AJEET NARAYAN - Metropolitan Magistrate",
  "centraldelhi;Tis Hazari Court Complex;786 Kahkashan Jabin - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 04",
  "centraldelhi;Tis Hazari Court Complex;787 MS. POOJA YADAV - JUDICIAL MAGISTRATE FIRST CLASS (MAHILA COURT) - 03",
  "centraldelhi;Tis Hazari Court Complex;789 SH. ARJUN KIRAR - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 05",
  "centraldelhi;Tis Hazari Court Complex;790 Ms.Ravisha Sidana - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 06",
  "centraldelhi;Tis Hazari Court Complex;791 SH. SAHIL MONGA - Metropolitan Magistrate",
  "centraldelhi;Tis Hazari Court Complex;795 Ms. Pooja Suhag - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 01",
  "centraldelhi;Tis Hazari Court Complex;796 SH. MAYANK AGGARWAL - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 02",
  "centraldelhi;Tis Hazari Court Complex;797 Shubhamjot Kaur Rakhra - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 03",
  "centraldelhi;Tis Hazari Court Complex;798 SH. CHANDRA BOSE - Presiding Officer, Special Court (NI Act)",
  "centraldelhi;Tis Hazari Court Complex;799 MS. DEEPIKA - JUDICIAL MAGISTRATE FIRST CLASS (DIGITAL TRAFFIC COURT)",
  "centraldelhi;Tis Hazari Court Complex;801 SH. ARVIND TOMAR - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 07",
  "centraldelhi;Tis Hazari Court Complex;802 SH. VAIBHAV GARG - JUDICIAL MAGISTRATE FIRST CLASS - 11",
  "centraldelhi;Tis Hazari Court Complex;803 MS. ARADHANA - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) DIGITAL COURT - 04",
  "centraldelhi;Tis Hazari Court Complex;804 MS. GOWRI REGHUNATH - JUDICIAL MAGISTRATE FIRST CLASS - 10",
  "centraldelhi;Tis Hazari Court Complex;805 MS. RICHIKA TYAGI - JUDICIAL MAGISTRATE FIRST CLASS - 12",
  "centraldelhi;Tis Hazari Court Complex;806 Rashi Raheja - JUDICIAL MAGISTRATE FIRST CLASS - 13",
  "centraldelhi;Tis Hazari Court Complex;807 MR. AKASH SHARMA - CIVIL JUDGE EVENING COURT - 08",
  "centraldelhi;Tis Hazari Court Complex;808 Sh. Sunil Khatri - CIVIL JUDGE EVENING COURT - 09",
  "centraldelhi;Tis Hazari Court Complex;809 Mr. Milan Goel - CIVIL JUDGE EVENING COURT - 10",
  "centraldelhi;Tis Hazari Court Complex;810 SURBHI GUPTA ANAND - JUDICIAL MAGISTRATE FIRST CLASS (NI ACT) - 08",
  "centraldelhi;Tis Hazari Court Complex;811 MS. ARADHANA - JUDICIAL MAGISTRATE FIRST CLASS NI ACT - 09",
  "centraldelhi;Tis Hazari Court Complex;11 Ms. Dhanashree Deka - Senior Civil Judge Cum Rent Controller",
  "centraldelhi;Tis Hazari Court Complex;12 Sh. Gopal Krishan - JSCC-cum-Addl. SCJ-cum-Guardian Judge-01",
  "centraldelhi;Tis Hazari Court Complex;31 Mr. Milan Goel - Civil Judge",
  "centraldelhi;Tis Hazari Court Complex;179 SH. SAHIL GUPTA - Civil Judge",
  "centraldelhi;Tis Hazari Court Complex;275 Hala Quamar - CIVIL JUDGE - 01",
  "centraldelhi;Tis Hazari Court Complex;296 SH. AKSHAY PRAKASH - CIVIL JUDGE - 04",
  "centraldelhi;Tis Hazari Court Complex;326 Ms. Aayushi Saxena - Civil Judge",
  "centraldelhi;Tis Hazari Court Complex;327 MR. BHARAT AGGARWAL - ACJ-cum-CCJ-cum-ARC",
  "centraldelhi;Tis Hazari Court Complex;406 Sh. Sunil Khatri - CIVIL JUDGE - 06",
  "centraldelhi;Tis Hazari Court Complex;434 Sh. Gaurav Goyal - Additional Rent Controller-01",
  "centraldelhi;Tis Hazari Court Complex;477 Mr. Devanshu Sajlan - CCJ cum Addl. Rent Controller",
  "centraldelhi;Tis Hazari Court Complex;517 MR. AAKASH SHARMA - CIVIL JUDGE - 02",
  "centraldelhi;Tis Hazari Court Complex;590 MS. DIVYA GUPTA - ADDITIONAL RENT CONTROLLER - 02",
  "centraldelhi;Tis Hazari Court Complex;593 MS. SANA KHAN - CIVIL JUDGE - 05",
  "centraldelhi;Tis Hazari Court Complex;797 MR. UMESH KUMAR - JSCC-cum-Addl. SCJ-cum-Guardian Judge-02",
  "centraldelhi;Tis Hazari Court Complex;798 SH. ARVIND DEV - CIVIL JUDGE - 09",
  "centraldelhi;Tis Hazari Court Complex;586 Vineeta Goyal - Principal Judge, Family Court, Central Dist.",
  "centraldelhi;Tis Hazari Court Complex;784 Tyagita Singh - Judge, Family Court",
  "centraldelhi;Tis Hazari Court Complex;785 Naveen Kumar Kashyap - JUDGE FAMILY COURT - 02",
  "centraldelhi;Tis Hazari Court Complex;1 Amit Kumar - PRESIDING OFFICER - APPELLATE TRIBUNAL MCD",
  "northdelhi;Rohini Court Complex;424 Ms Richa Manchanda - Presiding Off.-MACT",
  "northdelhi;Rohini Court Complex;426 Sh. Sidharth Mathur - District Judge",
  "northdelhi;Rohini Court Complex;431 Ms. Vandana - Additional Sessions Judge",
  "northdelhi;Rohini Court Complex;435 Sh. Viplav Dabas - ASJ/Spl.FTC North",
  "northdelhi;Rohini Court Complex;466 Sh. Prem Kumar Barthwal - Principal District and Sessions Judge, North",
  "northdelhi;Rohini Court Complex;496 Sh. Harvinder Singh Johal - ASJ/SPECIAL.JUDGE(NDPS)",
  "northdelhi;Rohini Court Complex;504 Sh. Sunil Kumar - Presiding Off.-MACT",
  "northdelhi;Rohini Court Complex;514 Sh. Amit Sahrawat - Additional Sessions Judge",
  "northdelhi;Rohini Court Complex;516 Sh. Jagmohan Singh - Additional Sessions Judge",
  "northdelhi;Rohini Court Complex;573 Sh. Sushil Kumar - Additional Sessions Judge",
  "northdelhi;Rohini Court Complex;576 Sh. Vikram Bali - District Judge",
  "northdelhi;Rohini Court Complex;757 Ms. Pooja Jain - Additional Sessions Judge",
  "northdelhi;Rohini Court Complex;758 Ms. Aanchal - District Judge",
  "northdelhi;Rohini Court Complex;760 Sh. Jagdish Kumar - District Judge (Commercial)",
  "northdelhi;Rohini Court Complex;761 Sh. Ravinder Singh II - District Judge",
  "northdelhi;Rohini Court Complex;762 Sh. Ajay Nagar - ASJ/Spl.FTC North",
  "northdelhi;Rohini Court Complex;763 Dr. Rakesh Kumar ll - District Judge (Commercial)",
  "northdelhi;Rohini Court Complex;434 Ms. Priyanka Rajpoot - Chief Judicial Magistrate",
  "northdelhi;Rohini Court Complex;436 Dr. Neha Kheria - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;443 Ms. Amardeep Kaur - Addl. Chief Judicial Magistrate",
  "northdelhi;Rohini Court Complex;460 MS. BHUJALI - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;462 Sh. Rohit Kumar - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;525 Ms. Sanya Dalal - Judicial Magistrate First Class (Mahila Court)-01",
  "northdelhi;Rohini Court Complex;528 Sh. Himanshu Sehloth - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;546 Ms. Garima Jindal - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;552 Ms. Bharti Beniwal - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;757 Dr. Neha Kheria - Judicial Magistrate First Class (Eve.Court-1)",
  "northdelhi;Rohini Court Complex;758 Ms. Renu - Civil Judge Evening Court-02",
  "northdelhi;Rohini Court Complex;759 Sh. Rohit Kumar - Judicial Magistrate First Class (Eve.Court-3)",
  "northdelhi;Rohini Court Complex;760 Ms. Jyoti Nain - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;761 Ms. Disha Singh - Judicial Magistrate First Class (Mahila Court)-02",
  "northdelhi;Rohini Court Complex;764 Sh. Gaurav Dahiya - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;765 Ms. Priyanka Gartan - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;766 Ms. Shreejee Abbot - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;767 Sh. Gaurav Dahiya - Judicial Magistrate First Class",
  "northdelhi;Rohini Court Complex;768 Ms. Bharti Beniwal - Judicial Magistrate First Class Eve. Court-4",
  "northdelhi;Rohini Court Complex;427 Sh. Ajay Singh Parihar - ACJ CUM ARC",
  "northdelhi;Rohini Court Complex;530 Sh. Nitish Kumar Sharma - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
  "northdelhi;Rohini Court Complex;534 Ms. Akriti Mahendru - Senior Civil Judge Cum Rent Controller",
  "northdelhi;Rohini Court Complex;566 Ms. Renu - Civil Judge",
  "northdelhi;Rohini Court Complex;556 Sh. Pankaj Gupta - Pr. Judge Family Court (North)",
  "northdelhi;Rohini Court Complex;558 Sh. Rajesh Kumar - Judge Family Court",
  "southdelhi;Saket Court Complex;6 Sh. SAMAR VISHAL - Additional Sessions Judge-02",
  "southdelhi;Saket Court Complex;8 Ms. Mona Tardi Kerketta - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;18 Sh. Gaurav Gupta - SPECIAL.JUDGE(NDPS)",
  "southdelhi;Saket Court Complex;38 Ms. Niti Phutela - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;49 Sh. Gurvinder Pal Singh - Principal District and Sessions Judge",
  "southdelhi;Saket Court Complex;56 MS. AMBIKA SINGH - District Judge - 01",
  "southdelhi;Saket Court Complex;64 Sh. Vivek Kr. Gulia - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;67 Sh. Ravindra Kr. Pandey - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;75 Ms. Anjani Mahajan - Presiding Off.-MACT",
  "southdelhi;Saket Court Complex;87 SH. MUNISH BANSAL - District Judge -03",
  "southdelhi;Saket Court Complex;202 SH. ARUL VARMA - District Judge - 02",
  "southdelhi;Saket Court Complex;205 SH. ABHITOSH PRATAP SINGH RATHORE - District Judge - 04",
  "southdelhi;Saket Court Complex;768 Ms.Manika - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;770 Ms. Savita Rao - District Judge (Commercial Court) - 01",
  "southdelhi;Saket Court Complex;771 Ms. Anuradha Shukla - District Judge (Commercial Court) - 02",
  "southdelhi;Saket Court Complex;773 Mr. Ajay Garg - Additional Sessions Judge Cum FTC",
  "southdelhi;Saket Court Complex;774 Sh. Ajay Kumar Jain - District Judge (Commercial Court) (Digital) 04",
  "southdelhi;Saket Court Complex;775 Sh. Sandeep Yadav - District Judge (Commercial Court) 03",
  "southdelhi;Saket Court Complex;776 Ms. Shunali Gupta - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;777 SH. HARGURVARINDER S. JAGGI - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;778 Sh.Purshotam Pathak - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;779 Sh. Pawan Kumar - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;781 SH. POORAN CHAND - District Judge -05",
  "southdelhi;Saket Court Complex;782 Ms. NABEELA WALI - Additional Sessions Judge -SC-RC",
  "southdelhi;Saket Court Complex;783 Sh. Dinesh Kumar - Additional Sessions Judge",
  "southdelhi;Saket Court Complex;784 Mr.Sunil Beniwal - District Judge - 06",
  "southdelhi;Saket Court Complex;785 Sh. Lokesh Kumar Sharma - District Judge (Commercial Court) 05",
  "southdelhi;Saket Court Complex;10 Ms. Ankita Bhatia - Judicial Magistrate First Class (NI Act)-03",
  "southdelhi;Saket Court Complex;17 Ms. Nidhi Singh - Judicial Magistrate First Class-03",
  "southdelhi;Saket Court Complex;20 Ms. Niharika Kumar Sharma - Chief Judicial Magistrate",
  "southdelhi;Saket Court Complex;23 Ms. Shikha Chahal - Judicial Magistrate First Class (Mahila Court)-01",
  "southdelhi;Saket Court Complex;25 Sh. Chatinder Singh - Judicial Magistrate First Class-04",
  "southdelhi;Saket Court Complex;27 MS. CHHAYA TYAGI - Judicial Magistrate First Class (Mahila Court)-02",
  "southdelhi;Saket Court Complex;34 Ms. Radha Kulshreshtha - Judicial Magistrate First Class (NI Act)-01",
  "southdelhi;Saket Court Complex;42 SH. BHANU PRATAP SINGH - Judicial Magistrate First Class-02",
  "southdelhi;Saket Court Complex;45 Ms. ARIBA KHAN - Judicial Magistrate First Class (NI Act)-02",
  "southdelhi;Saket Court Complex;46 MS. MEDHA ARYA - Additional Chief Judicial Magistrate",
  "southdelhi;Saket Court Complex;54 Ms. Neetika Kapoor - Judicial Magistrate First Class (Mahila Court)-03",
  "southdelhi;Saket Court Complex;81 SH. ASHISH KUMAR MEENA - Judicial Magistrate First Class-01",
  "southdelhi;Saket Court Complex;767 Sh. Shiva Parashar - Judicial Magistrate First Class (NI Act)-04",
  "southdelhi;Saket Court Complex;768 Ms. Jayanti Chander - Judicial Magistrate First Class - Evening Court 01",
  "southdelhi;Saket Court Complex;771 Sh. Nitin Shah - Judicial Magistrate First Class (NI Act)-05",
  "southdelhi;Saket Court Complex;772 MS. CHAKITA SRIVASTAVA - Judicial Magistrate First Class (Mahila Court)-04",
  "southdelhi;Saket Court Complex;773 Ms. Norma Jain - Judicial Magistrate First Class (NI Act) Digital Court-01",
  "southdelhi;Saket Court Complex;774 Ms. Pooja Kumari - Judicial Magistrate First Class (NI Act) Digital Court-02",
  "southdelhi;Saket Court Complex;775 Ms. Anshul Agnihotri - Judicial Magistrate First Class (NI Act) Digital Court-03",
  "southdelhi;Saket Court Complex;780 Ms. Nirmala Singh - Judicial Magistrate First Class-05",
  "southdelhi;Saket Court Complex;781 SH. SUKHJEET SINGH - Judicial Magistrate First Class-06",
  "southdelhi;Saket Court Complex;783 Ms. Archita Garg - Judicial Magistrate First Class (NI Act)-06",
  "southdelhi;Saket Court Complex;784 Ms. Jayanti Chander - Judicial Magistrate First Class (NI Act)-07",
  "southdelhi;Saket Court Complex;785 MR. AKSHAY SHARMA - Judicial Magistrate First Class (NI Act)-08",
  "southdelhi;Saket Court Complex;786 MS. KAMALDEEP KAUR - Judicial Magistrate First Class (Digital Traffic Court)",
  "southdelhi;Saket Court Complex;788 Ms. ARIBA KHAN - Judicial Magistrate First Class - Evening Court 02",
  "southdelhi;Saket Court Complex;789 SH. SUKHJEET SINGH - Judicial Magistrate First Class - Evening Court 03",
  "southdelhi;Saket Court Complex;790 MS. CHAKITA SRIVASTAVA - Judicial Magistrate First Class - Evening Court 04",
  "southdelhi;Saket Court Complex;791 MR. AKSHAY SHARMA - Judicial Magistrate First Class - Evening Court 05",
  "southdelhi;Saket Court Complex;792 Sidhant Krishan Singh - Judicial Magistrate First Class NI Act-09",
  "southdelhi;Saket Court Complex;793 Ms. Pooja Kumari - Judicial Magistrate First Class NI Act-10",
  "southdelhi;Saket Court Complex;794 Ms. Anshul Agnihotri - Judicial Magistrate First Class NI Act-11",
  "southdelhi;Saket Court Complex;47 Sh. Ankit Mittal - Civil Judge",
  "southdelhi;Saket Court Complex;55 MS. NEHA PRIYA - Senior Civil Judge Cum Rent Controller",
  "southdelhi;Saket Court Complex;57 Mr. Vipul Sandwar - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
  "southdelhi;Saket Court Complex;59 MS. SHILPI SINGH - Commercial Civil Judge CUM ARC CUM ADMIN-CJ",
  "southdelhi;Saket Court Complex;767 Yashdeep Chahal - Civil Judge",
  "southdelhi;Saket Court Complex;1 Sh. Sanjay Garg II - Principal Judge Family Court South District",
  "southdelhi;Saket Court Complex;2 Sh. Sunil Gupta - Judge, Family Court",
  "southdelhi;Saket Court Complex;3 Ms. Purva Sareen - Judge, Family Court",
  "northeast;Karkardooma Court Complex;5 Sh. Puneet Pahwa - ASJ/SPECIAL.JUDGE(NDPS)",
  "northeast;Karkardooma Court Complex;45 Sh. Shankar Narayanan - Additional Sessions Judge",
  "northeast;Karkardooma Court Complex;413 Sh. Ashwani Kumar Sarpal - Principal District and Sessions Judge - North-East District",
  "northeast;Karkardooma Court Complex;423 Ms. Twinkle Wadhwa - Additional Sessions Judge",
  "northeast;Karkardooma Court Complex;429 Sh. Aashish Gupta - District Judge",
  "northeast;Karkardooma Court Complex;442 Sh. Praveen Singh - Additional Sessions Judge",
  "northeast;Karkardooma Court Complex;476 Mr. Devender Nain - Presiding Officer-MACT",
  "northeast;Karkardooma Court Complex;763 Sh. Gorakh Nath Pandey - District Judge (Commercial Court)",
  "northeast;Karkardooma Court Complex;764 Ms. Richa Parihar - Additional Sessions Judge",
  "northeast;Karkardooma Court Complex;765 Ms. Gomati Manocha - District Judge",
  "northeast;Karkardooma Court Complex;766 Sh. Babru Bhan - Additional Sessions Judge",
  "northeast;Karkardooma Court Complex;767 Sh. Ajay Gulati-II - Additional Sessions Judge",
  "northeast;Karkardooma Court Complex;768 Sh. Balwinder Singh - Additional Sessions Judge",
  "northeast;Karkardooma Court Complex;18 Sh. Pankaj Rai - Judicial Magistrate First Class",
  "northeast;Karkardooma Court Complex;35 Ms. Tanya Bamniyal - Chief Judicial Magistrate",
  "northeast;Karkardooma Court Complex;63 Sh. Anmol Nohria - Judicial Magistrate First Class",
  "northeast;Karkardooma Court Complex;460 Sh. Tushar Gupta - Addl. Chief Judicial Magistrate",
  "northeast;Karkardooma Court Complex;462 Ms. Neha Barupal - Judicial Magistrate First Class (Mahila Court)-01",
  "northeast;Karkardooma Court Complex;763 Ms. Shruti Saraswat - Judicial Magistrate First Class",
  "northeast;Karkardooma Court Complex;765 Sh. Aakash Mohan Singh - Judicial Magistrate First Class (NI Act) Digital Court",
  "northeast;Karkardooma Court Complex;766 Ms. Neha Garg - Judicial Magistrate First Class (Mahila Court)-02",
  "northeast;Karkardooma Court Complex;767 Ms. Isra Zaidi - Judicial Magistrate First Class",
  "northeast;Karkardooma Court Complex;768 Ms. Pranjali Prakash - Judicial Magistrate First Class (Digital Traffic Court)",
  "northeast;Karkardooma Court Complex;769 Ms. Neha Garg - Judicial Magistrate First Class Evening Court-4",
  "northeast;Karkardooma Court Complex;770 Ms. Nishtha Mehtani - Judicial Magistrate First Class NI Act",
  "northeast;Karkardooma Court Complex;67 Ms. Tania Singh - Senior Civil Judge",
  "northeast;Karkardooma Court Complex;72 Sh. Animesh Bhaskar Mani Tripathi - ACJ/CCJ/ARC",
  "northeast;Karkardooma Court Complex;104 Sh. Ajay Kumar Malik - Judge-Small Cause Court",
  "northeast;Karkardooma Court Complex;1 Ms. Hemani Malhotra - Principal Judge, Family Court, North East Distt",
  "northeast;Karkardooma Court Complex;2 Sh. Ajay Singh Shekhawat - Judge Family Court-01",
  "northeast;Karkardooma Court Complex;3 Sh. Chander Jit Singh - Judge, Family Court-02",
  "southeastdelhi;Saket Court Complex;2 Ms. Charu Gupta - PO (MACT)-01",
  "southeastdelhi;Saket Court Complex;3 Sh. Ankit Singla - Additional Sessions Judge FTC -02",
  "southeastdelhi;Saket Court Complex;4 Sh. Vipin Kumar Rai - Additional Sessions Judge POCSO",
  "southeastdelhi;Saket Court Complex;9 Dr. Tarun Sahrawat - Additional Sessions Judge",
  "southeastdelhi;Saket Court Complex;10 Sh. Kuldeep Narayan - District Judge - 02",
  "southeastdelhi;Saket Court Complex;11 Ms. Nivedita Anil Sharma - Principal District and Sessions Judge",
  "southeastdelhi;Saket Court Complex;14 Sh. Rahul Bhatia - District Judge - 01",
  "southeastdelhi;Saket Court Complex;19 Pritam Singh - District Judge - 04",
  "southeastdelhi;Saket Court Complex;24 Sh. Anuj Aggarwal - Additional Sessions Judge",
  "southeastdelhi;Saket Court Complex;62 Ms. Sheetal Chaudhary Pradhan - Additional Sessions Judge",
  "southeastdelhi;Saket Court Complex;89 Sh. Sachin Mittal - District Judge - 03",
  "southeastdelhi;Saket Court Complex;201 Ms. Prabh Deep Kaur - District Judge - 05",
  "southeastdelhi;Saket Court Complex;204 Sh. Vishal Singh - Additional Sessions Judge",
  "southeastdelhi;Saket Court Complex;206 Ms. Neha - District Judge - 06",
  "southeastdelhi;Saket Court Complex;767 Sh. Anil Kumar Paswan - District Judge - 07",
  "southeastdelhi;Saket Court Complex;768 Ms. Anu Aggarwal - Additional Sessions Judge",
  "southeastdelhi;Saket Court Complex;771 Sh. Lal Singh - District Judge (Commercial Court)-01",
  "southeastdelhi;Saket Court Complex;773 Sh. Lalit Kumar - District Judge (Commercial Court)-02",
  "southeastdelhi;Saket Court Complex;774 Ms. Swati Sharma - Additional Sessions Judge FTSCPOCSO",
  "southeastdelhi;Saket Court Complex;775 Ms. Nirja Bhatia - District Judge (Commercial Court) (Digital)-07",
  "southeastdelhi;Saket Court Complex;776 Ms. Vrinda Kumari - District Judge (Commercial Court)-03",
  "southeastdelhi;Saket Court Complex;777 Ms. Sunena Sharma - District Judge (Commercial Court)-04",
  "southeastdelhi;Saket Court Complex;778 Ms. Neelam Singh - District Judge (Commercial Court)-05",
  "southeastdelhi;Saket Court Complex;779 Dr. Neera Bharihoke - District Judge (Commercial Court)-06",
  "southeastdelhi;Saket Court Complex;780 Ms. Shivani Chauhan - Additional Sessions Judge FTC-01",
  "southeastdelhi;Saket Court Complex;781 Sh. Vinod Kumar Gautam - Additional Sessions Judge FTC -02",
  "southeastdelhi;Saket Court Complex;782 Sh. Pranjal Aneja - Additional Sessions Judge (SC-RC)",
  "southeastdelhi;Saket Court Complex;787 Sh. Vipin Kharb - Additional Sessions Judge",
  "southeastdelhi;Saket Court Complex;790 Ms. Aditi Garg - PO (MACT)-02",
  "southeastdelhi;Saket Court Complex;791 Ms. Geetanjali - Additional Sessions Judge Cum FTC",
  "southeastdelhi;Saket Court Complex;792 Ms. Ankita Lal - Additional Sessions Judge (SC-POCSO)",
  "southeastdelhi;Saket Court Complex;793 Ms. Veena Rani - District Judge (Commercial Court) -08",
  "southeastdelhi;Saket Court Complex;5 Ms. Marilyn Joanna Khakha - Judicial Magistrate First Class (Mahila Court) - 03",
  "southeastdelhi;Saket Court Complex;13 Ms. Seema Nirmal - Judicial Magistrate First Class - 09",
  "southeastdelhi;Saket Court Complex;21 Sh. Raghav Sharma - Judicial Magistrate First Class - 06",
  "southeastdelhi;Saket Court Complex;22 Dr. Nupur Gupta - Chief Judicial Magistrate",
  "southeastdelhi;Saket Court Complex;26 Ms. Akansha Gautam - Judicial Magistrate First Class - 02",
  "southeastdelhi;Saket Court Complex;30 Ms. Aditi Rao - Judicial Magistrate First Class - 07",
  "southeastdelhi;Saket Court Complex;31 Dr. Aneeza Bishnoi - Judicial Magistrate First Class - 05",
  "southeastdelhi;Saket Court Complex;32 Ms. Shivangi Vyas - Judicial Magistrate First Class (Mahila Court) - 01",
  "southeastdelhi;Saket Court Complex;33 Ms. Aastha Sharma - Judicial Magistrate First Class (NI Act) - 03",
  "southeastdelhi;Saket Court Complex;41 Ms. Garima Garg - Judicial Magistrate First Class (NI Act) - 01",
  "southeastdelhi;Saket Court Complex;48 Sh. Vinod Joshi - Addl. Chief Judicial Magistrate",
  "southeastdelhi;Saket Court Complex;52 Sh. Bhavaya Karhail - Judicial Magistrate First Class - 08",
  "southeastdelhi;Saket Court Complex;61 Ms. Shruti Sharma-I - Judicial Magistrate First Class (NI Act) - 02",
  "southeastdelhi;Saket Court Complex;68 Ms. Neha Saini - Judicial Magistrate First Class (Mahila Court) - 02",
  "southeastdelhi;Saket Court Complex;83 Sh. Manuj Kaushal - Judicial Magistrate First Class - 03",
  "southeastdelhi;Saket Court Complex;84 Ms. Devanshi Janmeja - Judicial Magistrate First Class - 04",
  "southeastdelhi;Saket Court Complex;85 Sh. Rahul Jain - Judicial Magistrate First Class - 01",
  "southeastdelhi;Saket Court Complex;207 Ms. Seema Meena - Judicial Magistrate First Class (NI Act) - 04",
  "southeastdelhi;Saket Court Complex;767 Ms. Aditi Rao - Judicial Magistrate First Class (Evening Court-01)",
  "southeastdelhi;Saket Court Complex;768 Sh. Ajeet Narayan - Judicial Magistrate First Class (Evening Court -02)",
  "southeastdelhi;Saket Court Complex;771 Sh. Azad Sehrawat - Judicial Magistrate First Class - 10",
  "southeastdelhi;Saket Court Complex;773 Ms. Chhavi Bansal - Judicial Magistrate First Class - 11",
  "southeastdelhi;Saket Court Complex;777 Sh. Navdeep Gupta - Judicial Magistrate First Class (NI Act) Digital Court - 01",
  "southeastdelhi;Saket Court Complex;778 Mr. Ajay Narwal - Judicial Magistrate First Class (NI Act) Digital Court - 02",
  "southeastdelhi;Saket Court Complex;779 Sh. Prithvi Joshi - Judicial Magistrate First Class (NI Act) Digital Court - 03",
  "southeastdelhi;Saket Court Complex;781 Ms. Deepika Thakran - Judicial Magistrate First Class - 12",
  "southeastdelhi;Saket Court Complex;782 Ms. Shubhangi Srivastava - Judicial Magistrate First Class (NI Act) - 05",
  "southeastdelhi;Saket Court Complex;783 Ms. Nandini Garg - Judicial Magistrate First Class (Digital Traffic Court)",
  "southeastdelhi;Saket Court Complex;784 Ms. Aastha Sharma - Judicial Magistrate First Class Evening Court -03",
  "southeastdelhi;Saket Court Complex;785 Ms. Seema Meena - Judicial Magistrate First Class Evening Court -04",
  "southeastdelhi;Saket Court Complex;786 Ms. Shubhangi Srivastava - Judicial Magistrate First Class Evening Court -05",
  "southeastdelhi;Saket Court Complex;787 Sh. Anurag Chhabra - Judicial Magistrate First Class NI Act - 06",
  "southeastdelhi;Saket Court Complex;788 Sh. Mayank Aggarwal - Judicial Magistrate First Class NI Act - 07",
  "southeastdelhi;Saket Court Complex;789 Ms. Surbhi Sharma - Judicial Magistrate First Class NI Act - 08",
  "southeastdelhi;Saket Court Complex;790 Ms. Shivangi Vyas - Judicial Magistrate First Class (Mahila Court) - 01",
  "southeastdelhi;Saket Court Complex;15 Ms. Tarunpreet Kaur - Commercial Civil Judge CUM ARC CUM ADMIN-CJ",
  "southeastdelhi;Saket Court Complex;29 Sh. Ajeet Narayan - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
  "southeastdelhi;Saket Court Complex;44 Sh. Yashu Khurana - Civil Judge",
  "southeastdelhi;Saket Court Complex;50 Sh. Fahad Uddin - Senior Civil Judge Cum Rent Controller",
  "southeastdelhi;Saket Court Complex;768 Ms. Poorva Mehra - Civil Judge",
  "southeastdelhi;Saket Court Complex;769 Ms. Isha Thakur - Civil Judge",
  "southeastdelhi;Saket Court Complex;2 Sh. Nikhil Chopra - Principal Judge, Family Court, South East Dist.",
  "southeastdelhi;Saket Court Complex;3 Ms. Monika Saroha - Judge, Family Court",
  "southeastdelhi;Saket Court Complex;4 Ms. Namrita Aggarwal - Judge, Family Court",
  "westdelhi;Tiz Hazari Court Complex;22 Dr. Aditi Choudhary - Principal District and Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;138 Sh. Vineet Kumar - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;156 Sh. Satvir Singh Lamba - Special Judge",
  "westdelhi;Tiz Hazari Court Complex;158 SH. SHIV KUMAR - District Judge",
  "westdelhi;Tiz Hazari Court Complex;201 Sh. Dharmender Singh - District Judge",
  "westdelhi;Tiz Hazari Court Complex;234 Sh. Vijay Shankar - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;450 Sh. Mukesh Kumar - Presiding Off.-MACT",
  "westdelhi;Tiz Hazari Court Complex;452 Sh. Gopal Singh Chauhan - District Judge",
  "westdelhi;Tiz Hazari Court Complex;472 Sh. Divyang Thakur - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;476 MS. GUNJAN GUPTA - Presiding Off.-MACT",
  "westdelhi;Tiz Hazari Court Complex;541 DR. YADVENDER SINGH - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;558 Satyabrata Panda - Additional Sessions Judge (FTC)",
  "westdelhi;Tiz Hazari Court Complex;582 Dr. Saurabh Kulshreshtha - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;601 Sh. Arvind Bansal - District Judge",
  "westdelhi;Tiz Hazari Court Complex;604 SH. ANIL CHANDHEL - District Judge",
  "westdelhi;Tiz Hazari Court Complex;607 Goma Dabas Gupta - District Judge",
  "westdelhi;Tiz Hazari Court Complex;778 Sh. Nipun Awasthi - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;783 Ms. Shelly Arora - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;784 SH. SACHIN JAIN - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;789 Sh. Ashutosh Kumar - DISTRICT JUDGE (COMMERCIAL COURT) - 01, WEST, THC",
  "westdelhi;Tiz Hazari Court Complex;790 Preeti Aggarwal Gupta - DISTRICT JUDGE (COMMERCIAL COURT) - 02, WEST, THC",
  "westdelhi;Tiz Hazari Court Complex;791 Priya Mahendra - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;793 SH. MANOJ KR. SHARMA - District Judge",
  "westdelhi;Tiz Hazari Court Complex;794 Deepak kumar II - Additional Sessions Judge (FTC)",
  "westdelhi;Tiz Hazari Court Complex;795 Saloni Singh - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;796 Ms.Kadambari Awasthi - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;797 Ms. Babita Puniya - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;798 RAGHUBIR SINGH - DISTRICT JUDGE (COMMERCIAL COURT) - 03, WEST, THC",
  "westdelhi;Tiz Hazari Court Complex;799 Sh. Siddhartha Malik - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;800 Vishal Pahuja - ADDITIONAL SESSIONS JUDGE SC-RC - 01",
  "westdelhi;Tiz Hazari Court Complex;801 Pooja Talwar - Additional Sessions Judge (FTC)",
  "westdelhi;Tiz Hazari Court Complex;802 Ms. Saumya Chauhan - Additional Sessions Judge (FTC)",
  "westdelhi;Tiz Hazari Court Complex;803 SH. ANKIT MEHTA - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;804 Harish Kumar - DISTRICT JUDGE (COMMERCIAL COURT) - 04, WEST, THC",
  "westdelhi;Tiz Hazari Court Complex;805 Sh. Raj Kumar Tripathi - DISTRICT JUDGE (COMMERCIAL COURT) - 05, WEST, THC",
  "westdelhi;Tiz Hazari Court Complex;806 Sh. Naresh Kumar Malhotra - DISTRICT JUDGE (COMMERCIAL COURT) - 06, WEST, THC",
  "westdelhi;Tiz Hazari Court Complex;807 Mr.Rajinder Singh - Additional Sessions Judge",
  "westdelhi;Tiz Hazari Court Complex;808 Sh. Naveen Gupta - District Judge",
  "westdelhi;Tiz Hazari Court Complex;809 Vinod Kumar Meena - District Judge",
  "westdelhi;Tiz Hazari Court Complex;810 Susheel Bala Dagar - District Judge",
  "westdelhi;Tiz Hazari Court Complex;40 MS. SURABHI SETHI - Judicial Magistrate First Class (NI ACT) - 02",
  "westdelhi;Tiz Hazari Court Complex;145 MS. UDITA JAIN GARG - Additional Chief Judicial Magistrate",
  "westdelhi;Tiz Hazari Court Complex;178 Sh. Tanmay Batham - Judicial Magistrate First Class (NI ACT) - 03",
  "westdelhi;Tiz Hazari Court Complex;210 Mr. Gaurav Singal - Judicial Magistrate First Class - 06",
  "westdelhi;Tiz Hazari Court Complex;252 MS. DIVYASHREE RAINA - Judicial Magistrate First Class (Mahila Court) - 04",
  "westdelhi;Tiz Hazari Court Complex;367 Ms. Shivli Talwar - Judicial Magistrate First Class (Mahila Court) - 01",
  "westdelhi;Tiz Hazari Court Complex;467 Vasundhara Azad - Chief Judicial Magistrate",
  "westdelhi;Tiz Hazari Court Complex;468 SH. SHASHANK NANDAN BHAT - Judicial Magistrate First Class - 02",
  "westdelhi;Tiz Hazari Court Complex;469 Ms. KOMAL GARG - Judicial Magistrate First Class - 03",
  "westdelhi;Tiz Hazari Court Complex;480 Ankur Panghal - Judicial Magistrate First Class - 05",
  "westdelhi;Tiz Hazari Court Complex;499 Ms. Ritu Singh - Chief Judicial Magistrate",
  "westdelhi;Tiz Hazari Court Complex;514 Mr. Gaurav Ujjwal - Judicial Magistrate First Class (NI ACT) - 01",
  "westdelhi;Tiz Hazari Court Complex;516 Sh. Anshul Singhal - Judicial Magistrate First Class - 04",
  "westdelhi;Tiz Hazari Court Complex;519 Komal - Judicial Magistrate First Class - 01",
  "westdelhi;Tiz Hazari Court Complex;555 MS. Shruti Sharma-II - Judicial Magistrate First Class (Mahila Court) - 02",
  "westdelhi;Tiz Hazari Court Complex;557 Deepika Goyal Shokeen - Judicial Magistrate First Class (Mahila Court) - 03",
  "westdelhi;Tiz Hazari Court Complex;781 SH. SHASHANK NANDAN BHAT - Judicial Magistrate First Class Evening Court - 01",
  "westdelhi;Tiz Hazari Court Complex;782 Ms. KOMAL GARG - Judicial Magistrate First Class Evening Court - 02",
  "westdelhi;Tiz Hazari Court Complex;789 Ms. Disha Langan - Judicial Magistrate First Class (Mahila Court) - 05",
  "westdelhi;Tiz Hazari Court Complex;790 Sh. Deepak Kumar-I - Metropolitan Magistrate",
  "westdelhi;Tiz Hazari Court Complex;792 Poonam Singh - Judicial Magistrate First Class (NI ACT) - 04",
  "westdelhi;Tiz Hazari Court Complex;793 MR. ANKIT KARAN SINGH - Judicial Magistrate First Class - 08",
  "westdelhi;Tiz Hazari Court Complex;795 Sh. Vikas Madaan - Judicial Magistrate First Class - 07",
  "westdelhi;Tiz Hazari Court Complex;796 Abhay Choudhary - Judicial Magistrate First Class (NI ACT) Digital Court - 01",
  "westdelhi;Tiz Hazari Court Complex;797 Shivangi Mangla - Judicial Magistrate First Class (NI ACT) Digital Court - 02",
  "westdelhi;Tiz Hazari Court Complex;798 Atisha Jain - Judicial Magistrate First Class (Digital Traffic Court)",
  "westdelhi;Tiz Hazari Court Complex;799 MS. ANAMIKA - Judicial Magistrate First Class (Mahila Court) - 06",
  "westdelhi;Tiz Hazari Court Complex;800 Deshna Golechha - Judicial Magistrate First Class (NI ACT) Digital Court - 03",
  "westdelhi;Tiz Hazari Court Complex;801 Shraddha Srivastava - Judicial Magistrate First Class - 09",
  "westdelhi;Tiz Hazari Court Complex;802 Moksha Bains - Judicial Magistrate First Class - 11",
  "westdelhi;Tiz Hazari Court Complex;803 Ms. Aishwarya Singh Kashyap - Judicial Magistrate First Class - 10",
  "westdelhi;Tiz Hazari Court Complex;804 Sheetal Rani - Judicial Magistrate First Class - 12",
  "westdelhi;Tiz Hazari Court Complex;805 Sh. Lalit Kumar - Judge Evening Court - 05",
  "westdelhi;Tiz Hazari Court Complex;806 Sh. Kautuk Bhardwaj - Judge Evening Court - 06",
  "westdelhi;Tiz Hazari Court Complex;807 Shivangi Mangla - Judicial Magistrate First Class NI ACT - 05",
  "westdelhi;Tiz Hazari Court Complex;3 MS. NEHA PANDEY - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
  "westdelhi;Tiz Hazari Court Complex;118 Ishita Bhardwaj - Civil Judge",
  "westdelhi;Tiz Hazari Court Complex;125 Sh. Kautuk - Civil Judge",
  "westdelhi;Tiz Hazari Court Complex;178 MR. ANSHUL MEHTA - ACJ-cum-CCJ-cum-ARC",
  "westdelhi;Tiz Hazari Court Complex;252 MS. RICHA SHARMA - Senior Civil Judge Cum Rent Controller",
  "westdelhi;Tiz Hazari Court Complex;277 Sh. Lalit Kumar - Civil Judge - 02",
  "westdelhi;Tiz Hazari Court Complex;474 MS. ALKA SINGH - CCJ cum Addl. Rent Controller",
  "westdelhi;Tiz Hazari Court Complex;797 Sh. Vivek Kumar Agarwal - JSCC-cum-ASCJ-cum-Guardian Judge - 02",
  "westdelhi;Tiz Hazari Court Complex;798 MR. DEV SAROHA - Civil Judge - 04",
  "westdelhi;Tiz Hazari Court Complex;587 Sh. Vijay Kumar Dahiya - Principal Judge, Family Court, West Dist.",
  "westdelhi;Tiz Hazari Court Complex;588 Manish Gupta - Judge, Family Court",
  "westdelhi;Tiz Hazari Court Complex;785 Sh. Lovleen - Judge, Family Court",
  "southwestdelhi;Dwarka Court Complex;422 Ms. Harleen Singh - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;424 Ms. Shilpi M. Jain - District Judge",
  "southwestdelhi;Dwarka Court Complex;435 Ms. Rashmi Gupta - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;437 Sh. Harjyot Singh Bhalla - District Judge",
  "southwestdelhi;Dwarka Court Complex;438 Sh. Rakesh Kumar Singh - Presiding Officer-MACT-01",
  "southwestdelhi;Dwarka Court Complex;440 Ms. Vandana Jain - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;458 Ms. Bhavna Kalia - ASJ/SPECIAL.JUDGE(NDPS)",
  "southwestdelhi;Dwarka Court Complex;464 Sh. Pawan Kumar Jain - Principal District and Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;467 Ms. Rajat Goyal - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;501 Ms. Shivali Bansal - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;515 Sh. Manoj Kumar II - District Judge",
  "southwestdelhi;Dwarka Court Complex;518 Sh. Sumit Dalal - District Judge",
  "southwestdelhi;Dwarka Court Complex;546 Ms. Richa Gusain Solanki - District Judge",
  "southwestdelhi;Dwarka Court Complex;759 Mr. Raj Kumar - District Judge (Commercial Court)-01",
  "southwestdelhi;Dwarka Court Complex;760 Sh. Sushil Anuj Tyagi - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;761 Sh. Sudeep Raj Saini - Presiding Officer-MACT-02",
  "southwestdelhi;Dwarka Court Complex;762 Sh. Vaibhav Mehta - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;763 Sh. Santosh Kumar Singh - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;764 Sh. Anurag Dass - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;765 Ms. Gurmohina Kaur - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;766 Sh. Deepak Wason - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;767 Sh. Gautam Manan - District Judge (Commercial Court)-03",
  "southwestdelhi;Dwarka Court Complex;768 Sh. Balwant Rai Bansal - District Judge (Commercial Court)-02",
  "southwestdelhi;Dwarka Court Complex;769 Sh. Himanshu Raman Singh - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;770 Sh. Rohit Gulia - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;771 Sh. Rakesh Pandit - District Judge (Commercial Court)-04",
  "southwestdelhi;Dwarka Court Complex;772 Ms. Manu Goel Kharb - ASJ/SPECIAL.JUDGE(NDPS)",
  "southwestdelhi;Dwarka Court Complex;773 Ms. Mahima Rai Singh - Additional Sessions Judge",
  "southwestdelhi;Dwarka Court Complex;400 Ms. Surbhi - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;421 Ms. Deepali Srivastava - Additional Chief Judicial Magistrate",
  "southwestdelhi;Dwarka Court Complex;423 Ms. Pallavi Tyagi - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;428 Ms. Neelmani Sharma - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;433 Ms. Divya Singh - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;442 Sh. Harshal Negi - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;444 Dr. Priya Janghu - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;450 Ms. Divya Yadav - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;453 Ms. Apoorva Rana - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;454 Mr. Rahul Katare - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;460 Sh. Saurabh Goyal - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;496 Ms. Kritika Jain - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;497 Sh. Rishabh Kapoor - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;498 Ms. Surabhi Rastogi - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;514 Ms. Divya Arora - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;542 Mr. Rahul Katare - Judicial Magistrate First Class (Evening Court-1)",
  "southwestdelhi;Dwarka Court Complex;543 Ms. Deepika Yadav - Judicial Magistrate First Class (Evening Court-2)",
  "southwestdelhi;Dwarka Court Complex;544 Sh. Ajay Narwal - Judicial Magistrate First Class (Evening Court-3)",
  "southwestdelhi;Dwarka Court Complex;545 Ms. Sonica Meena - Judicial Magistrate First Class (Evening Court-4)",
  "southwestdelhi;Dwarka Court Complex;548 Ms. Deeksha Rao - Municipal Magistrate",
  "southwestdelhi;Dwarka Court Complex;551 Ms. Samiksha Gupta - Chief Judicial Magistrate",
  "southwestdelhi;Dwarka Court Complex;553 Ms. Sukriti Jha - Judicial Magistrate First Class (Evening Court-5)",
  "southwestdelhi;Dwarka Court Complex;554 Ms. Divya Singh - Judicial Magistrate First Class (Evening Court-6)",
  "southwestdelhi;Dwarka Court Complex;558 Ms. Shubhi Gupta - Judicial Magistrate First Class (Evening Court-7)",
  "southwestdelhi;Dwarka Court Complex;559 Ms. Vinerjeet Kaur - Judicial Magistrate First Class (Evening Court-8)",
  "southwestdelhi;Dwarka Court Complex;757 Ms. Kirandeep Kaur - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;758 Sh. Shiv Kumar - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;759 Ms. Vinerjeet Kaur - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;760 Ms. Shubhangi Aggarwal - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;761 Ms. Ashima Lakhanpall - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;763 Sh. Shubham Gupta - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;764 Ms. Sonica Meena - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;765 Sh. Anurag Chhabra - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;766 Sh. Kawal Singh - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;767 Ms. Surbhi Gupta Anand - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;768 Ms. Deepika Yadav - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;769 Sh. Anubhav Bijalwan - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;770 Ms. Shreya Singh - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;771 Ms. Nandini Sharma - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;772 Ms. Deeksha Sethi - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;773 Sh. Abhinav Ahlawat - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;774 Sh. Nidhish Kumar Meena - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;775 Ms. Shubhi Gupta - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;776 Sh. Harjot Singh Aujla - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;778 Sh. Nitesh Goel - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;785 Sh. Mayank Singhal - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;787 Ms. Bhawna Rattan - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;788 Sh. Amit Rana - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;790 Ms. Anuradha Sonker - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;791 Ms. Sukriti Jha - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;792 Ms. Parul Sharma - Judicial Magistrate First Class",
  "southwestdelhi;Dwarka Court Complex;793 Ms. Divya Yadav - Judicial Magistrate First Class (Evening Court-9)",
  "southwestdelhi;Dwarka Court Complex;425 Sh. Anubhav Sharma - Civil Judge",
  "southwestdelhi;Dwarka Court Complex;439 Sh. Sukhman Sandhu - Administrative Civil Judge cum Addl. Rent Controller",
  "southwestdelhi;Dwarka Court Complex;531 Ms. Tapasya Agarwal - Judge Incharge - SCJ cum RC",
  "southwestdelhi;Dwarka Court Complex;532 Sh. Vaibhav Chaurasia - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
  "southwestdelhi;Dwarka Court Complex;757 Sh. Sarthak Panwar - Civil Judge",
  "southwestdelhi;Dwarka Court Complex;758 Sh. Suneet Anand - Civil Judge",
  "southwestdelhi;Dwarka Court Complex;449 Sh. Pitamber Dutt - Principal Judge, Family Court",
  "southwestdelhi;Dwarka Court Complex;503 Ms. Niyay Bindu - Judge, Family Court-01",
  "southwestdelhi;Dwarka Court Complex;757 Ms. Navita Kumari Bagha - Additional Principal Judge",
  "southwestdelhi;Dwarka Court Complex;1 Ms. Chitranshi Arora - Principal Magistrate",
  "rohini;Rohini Court Complex;423 Ms. Rajani Ranga - Additional Sessions Judge",
  "rohini;Rohini Court Complex;425 Ms. Nisha Sahay Saxena - Principal District and Sessions Judge, North West",
  "rohini;Rohini Court Complex;430 Sh. Vikram - ADJ1(NW)/MACT",
  "rohini;Rohini Court Complex;432 Sh. Shivaji Anand - ASJ/SPECIAL.JUDGE(NDPS)",
  "rohini;Rohini Court Complex;439 Sh. Kapil Kumar - ASJ/FTC NW",
  "rohini;Rohini Court Complex;449 Ms. Deepika Singh - Presiding Off.-MACT",
  "rohini;Rohini Court Complex;499 Sh. Muneesh Garg - Additional Sessions Judge",
  "rohini;Rohini Court Complex;503 Ms. Kiran Gupta - District Judge (North-West)",
  "rohini;Rohini Court Complex;505 Sh. Ashish Aggarwal - District Judge",
  "rohini;Rohini Court Complex;515 Sh. Prashant Kumar - Additional Sessions Judge",
  "rohini;Rohini Court Complex;572 Ms. Jasjeet Kaur - Additional Sessions Judge",
  "rohini;Rohini Court Complex;575 Sh. Rakesh Kumar V - District Judge",
  "rohini;Rohini Court Complex;758 Sh. Devender Kumar Jangala - District Judge (Commercial) - 01",
  "rohini;Rohini Court Complex;759 Mr. Rajinder Kumar - Additional Sessions Judge",
  "rohini;Rohini Court Complex;760 Ms. Neeti Suri Mishra - ASJ/FTC NW",
  "rohini;Rohini Court Complex;761 Sh. Vinod Yadav - District Judge (Commercial) - 02",
  "rohini;Rohini Court Complex;450 Ms. Aishwarya Sharma - Judicial Magistrate First Class (Mahila Court)-01",
  "rohini;Rohini Court Complex;459 Ms. Upasana Satija - Chief Judicial Magistrate",
  "rohini;Rohini Court Complex;461 Ms. Reetika Jain - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;519 Ms. Anuradha Jindal - Addl. Chief Judicial Magistrate",
  "rohini;Rohini Court Complex;520 Ms. Ebbani Aggarwal - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;526 Sh. Abhinav Singh - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;527 Sh. Apoorv Bhardwaj - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;547 Ms. Nitika - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;551 Sh. Sanyam Jain - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;578 Ms. Neha Goel - Judicial Magistrate First Class (Mahila Court)-02",
  "rohini;Rohini Court Complex;758 Ms. Anuradha Jindal - Judicial Magistrate First Class (Evening Court-1)",
  "rohini;Rohini Court Complex;759 Sh. Sanyam Jain - Judicial Magistrate First Class (Evening Court-2)",
  "rohini;Rohini Court Complex;760 Ms. Reetika Jain - Judicial Magistrate First Class (Evening Court-3)",
  "rohini;Rohini Court Complex;762 Ms. Shagun - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;763 Sh. Gaurav Katariya - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;766 Sh. Kashish Bajaj - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;767 Ms. Shraddha Tripathi - Judicial Magistrate First Class",
  "rohini;Rohini Court Complex;769 Sh. Prithvi Joshi - Judicial Magistrate First Class Evening Court-4",
  "rohini;Rohini Court Complex;531 Sh. Mayank Mittal - Senior Civil Judge Cum Rent Controller",
  "rohini;Rohini Court Complex;532 Sh. Gaurav Sharma - JSCC-cum-Addl. SCJ-cum-Guardian Judge",
  "rohini;Rohini Court Complex;533 Ms. Gita - ACJ CUM ARC",
  "rohini;Rohini Court Complex;582 Sh. Vaibhav Kumar - Civil Judge",
  "rohini;Rohini Court Complex;559 Sh. Umed Singh - Principal Judge, Family Courts (NW)",
  "rohini;Rohini Court Complex;561 Sh. Hem Raj - Judge Family Court",
  "shahdara;Karkardooma Court Complex;108 Ms. Surabhi Sharma Vats - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;111 Ms. Charu Aggarwal - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;129 Sh. Munish Markan - Additional Sessions Judge - POCSO",
  "shahdara;Karkardooma Court Complex;445 Sh. Vijay Kumar Jha - Presiding Officer-MACT",
  "shahdara;Karkardooma Court Complex;464 Sh. Sanjay Sharma I - Principal District and Sessions Judge - Shahdara District",
  "shahdara;Karkardooma Court Complex;468 Sh. Gaurav - District Judge",
  "shahdara;Karkardooma Court Complex;477 Sh. Sameer Bajpai - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;762 Sh. Ankur Jain-II - District Judge",
  "shahdara;Karkardooma Court Complex;764 Dr. Sumedh Kumar Sethi - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;765 Ms. Aakanksha Vyas - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;766 Sh. SUDESH KUMAR II - District Judge (Commercial Court)",
  "shahdara;Karkardooma Court Complex;767 Ms. Kiran Bansal - District Judge (Commercial Court)-02",
  "shahdara;Karkardooma Court Complex;768 Sh. Sanjay Sharma-II - District Judge (Commercial Court) 03",
  "shahdara;Karkardooma Court Complex;769 Sh. Pawan Kumar Matto - District Judge (Commercial Court) 04",
  "shahdara;Karkardooma Court Complex;770 Ms. Preeti Agarwala - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;771 Mohammad Ehtesham - District Judge",
  "shahdara;Karkardooma Court Complex;772 Sh. Kumar Rajat - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;773 Ms. Manisha Tripathy - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;774 Sh. Harun Pratap - Presiding Officer-MACT",
  "shahdara;Karkardooma Court Complex;775 Sh. Gajender Singh Nagar - Special Judge",
  "shahdara;Karkardooma Court Complex;776 Sh. Deepanker Mohan - District Judge",
  "shahdara;Karkardooma Court Complex;777 Sh. Harvinder Singh - Additional Sessions Judge",
  "shahdara;Karkardooma Court Complex;23 Ms. Shipra Dhankar - Judicial Magistrate First Class (Mahila Court)-01",
  "shahdara;Karkardooma Court Complex;74 Ms. Sanghmitra - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;455 Sh. Mohit Sharma - Chief Judicial Magistrate",
  "shahdara;Karkardooma Court Complex;456 Ms. Deepakshi Rana - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;467 Kanika Agarwal - Judicial Magistrate First Class (Mahila Court)-02",
  "shahdara;Karkardooma Court Complex;469 Sh. Manish Jain - Addl. Chief Judicial Magistrate",
  "shahdara;Karkardooma Court Complex;762 Sh. Akhil Malik - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;763 Ms. Nidhi Bala - Judicial Magistrate First Class (Mahila Court)-03",
  "shahdara;Karkardooma Court Complex;764 Sh. Udbhav Kumar Jain - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;765 Ms. Anushtha Srivastava - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;766 Ms. Arushi Parwal - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;767 Ms. Nishi Jindal - Judicial Magistrate First Class (NI Act) Digital Court",
  "shahdara;Karkardooma Court Complex;770 Ms. Karuna - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;775 Shazadi Halima Sadiya - Judicial Magistrate First Class (Digital Traffic Court)",
  "shahdara;Karkardooma Court Complex;776 Ms. Manisha Bhau - Judicial Magistrate First Class NI Act",
  "shahdara;Karkardooma Court Complex;777 Sh. Rahul Saini - Judicial Magistrate First Class",
  "shahdara;Karkardooma Court Complex;778 Sh. Vinod Kumar - Judicial Magistrate First Class (NI Act) Digital Court",
  "shahdara;Karkardooma Court Complex;779 Sh. Udbhav Kumar Jain - Judicial Magistrate First Class-Evening Court-04",
  "shahdara;Karkardooma Court Complex;20 Ms Pragati - Senior Civil Judge",
  "shahdara;Karkardooma Court Complex;73 Ms. Arjinder Kaur - Judge-Small Cause Court",
  "shahdara;Karkardooma Court Complex;428 Ms. Charu Asiwal - ACJ/CCJ/ARC",
  "shahdara;Karkardooma Court Complex;762 Sh. Jitender - Civil Judge-01",
  "shahdara;Karkardooma Court Complex;763 Sh. Varun Chandra - Civil Judge-02",
  "shahdara;Karkardooma Court Complex;765 Padma Ladol - Civil Judge-03",
  "shahdara;Karkardooma Court Complex;480 Sh. Sanjeev Aggarwal - Principal Judge, Family Court, Shahdara",
  "shahdara;Karkardooma Court Complex;762 Ms. Savitri - Judge, Family Court-02",
  "shahdara;Karkardooma Court Complex;763 Sh. Sumit Dass - Judge Family Court-01",
  "shahdara;Karkardooma Court Complex;764 Ms. Riya Guha - Judge Family Court-03",
  "shahdara;Karkardooma Court Complex;1 Ms. Akanksha Garg - Principal Magistrate JJB-VI"
]

module.exports = {delhiCourtFlatList}